services:
  service:
    image: ${REGISTRY_IMAGE}
    container_name: ${SERVICE_NAME}_service
    networks:
      - backend
    restart: unless-stopped
    environment:
      - BRAND_NAME="Calendaria"
      - DEBUG=1
      - TOKEN_DURATION=2h
      - REFRESH_TOKEN_DURATION=30d
      - SERVICE_NAME=${SERVICE_NAME}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID_PATH=/run/secrets/vault_secret_id
      - OTLP_GRPC_ADDRESS=${OTLP_GRPC_ADDRESS}
    command: ["./app"]
    secrets:
      - vault_secret_id

networks:
  backend:
    name: ${NETWORK}
    driver: bridge
    external: true

secrets:
  vault_secret_id:
    environment: 'VAULT_SECRET_ID'
