// Code generated by ent, DO NOT EDIT.

package userprivacy

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.calendaria.team/services/iam/ent/property"
)

const (
	// Label holds the string label denoting the userprivacy type in the database.
	Label = "user_privacy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSetting holds the string denoting the setting field in the database.
	FieldSetting = "setting"
	// FieldOption holds the string denoting the option field in the database.
	FieldOption = "option"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userprivacy in the database.
	Table = "user_privacies"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_privacies"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userprivacy fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSetting,
	FieldOption,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// SettingValidator is a validator for the "setting" field enum values. It is called by the builders before save.
func SettingValidator(s property.PrivacySettings) error {
	switch s {
	case "MY_LAST_ACTIONS", "MY_PROFILE_IMAGE", "MY_EVENTS", "GROUP_CHAT_INVITE", "EVENT_INVITE":
		return nil
	default:
		return fmt.Errorf("userprivacy: invalid enum value for setting field: %q", s)
	}
}

// OptionValidator is a validator for the "option" field enum values. It is called by the builders before save.
func OptionValidator(o property.PrivacyOptions) error {
	switch o {
	case "ALL", "MY_CONTACTS", "NO_ONE":
		return nil
	default:
		return fmt.Errorf("userprivacy: invalid enum value for option field: %q", o)
	}
}

// OrderOption defines the ordering options for the UserPrivacy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySetting orders the results by the setting field.
func BySetting(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetting, opts...).ToFunc()
}

// ByOption orders the results by the option field.
func ByOption(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOption, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
