// Code generated by ent, DO NOT EDIT.

package userprivacy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.calendaria.team/services/iam/ent/enum"
	"gitlab.calendaria.team/services/iam/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldEQ(FieldUserID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldNotIn(FieldUserID, vs...))
}

// SettingEQ applies the EQ predicate on the "setting" field.
func SettingEQ(v enum.PrivacySettings) predicate.UserPrivacy {
	vc := v
	return predicate.UserPrivacy(sql.FieldEQ(FieldSetting, vc))
}

// SettingNEQ applies the NEQ predicate on the "setting" field.
func SettingNEQ(v enum.PrivacySettings) predicate.UserPrivacy {
	vc := v
	return predicate.UserPrivacy(sql.FieldNEQ(FieldSetting, vc))
}

// SettingIn applies the In predicate on the "setting" field.
func SettingIn(vs ...enum.PrivacySettings) predicate.UserPrivacy {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserPrivacy(sql.FieldIn(FieldSetting, v...))
}

// SettingNotIn applies the NotIn predicate on the "setting" field.
func SettingNotIn(vs ...enum.PrivacySettings) predicate.UserPrivacy {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserPrivacy(sql.FieldNotIn(FieldSetting, v...))
}

// OptionEQ applies the EQ predicate on the "option" field.
func OptionEQ(v enum.PrivacyOptions) predicate.UserPrivacy {
	vc := v
	return predicate.UserPrivacy(sql.FieldEQ(FieldOption, vc))
}

// OptionNEQ applies the NEQ predicate on the "option" field.
func OptionNEQ(v enum.PrivacyOptions) predicate.UserPrivacy {
	vc := v
	return predicate.UserPrivacy(sql.FieldNEQ(FieldOption, vc))
}

// OptionIn applies the In predicate on the "option" field.
func OptionIn(vs ...enum.PrivacyOptions) predicate.UserPrivacy {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserPrivacy(sql.FieldIn(FieldOption, v...))
}

// OptionNotIn applies the NotIn predicate on the "option" field.
func OptionNotIn(vs ...enum.PrivacyOptions) predicate.UserPrivacy {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserPrivacy(sql.FieldNotIn(FieldOption, v...))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserPrivacy {
	return predicate.UserPrivacy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserPrivacy {
	return predicate.UserPrivacy(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserPrivacy) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserPrivacy) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserPrivacy) predicate.UserPrivacy {
	return predicate.UserPrivacy(sql.NotPredicates(p))
}
