// Code generated by ifacemaker; DO NOT EDIT.

package data

import (
	"context"

	notifications_v1 "gitlab.calendaria.team/services/notifications/api/notifications/v1"
)

// INotificationsRemote ...
type INotificationsRemote interface {
	GetSenderClient(ctx context.Context) (notifications_v1.SenderClient, error)
	PersonalSmsSender(ctx context.Context, phone, message string) error
	PersonalEmailSender(ctx context.Context, email, emailType, language string, data map[string]string) error
}
