// Code generated by ifacemaker; DO NOT EDIT.

package data

import (
	"context"

	tenants_v1 "gitlab.calendaria.team/services/tenants/api/tenants/v1"
)

// ITenantRemote ...
type ITenantRemote interface {
	CreateTenants(ctx context.Context, name string) (*tenants_v1.Tenant, error)
	GetUserTenants(ctx context.Context) ([]*tenants_v1.Tenant, error)
	GetMemberIdentities(ctx context.Context, tenantId, userId int64) (*tenants_v1.GetMemberIdentitiesReply, error)
}
