// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/remote/contacts.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIContactsRemote is a mock of IContactsRemote interface.
type MockIContactsRemote struct {
	ctrl     *gomock.Controller
	recorder *MockIContactsRemoteMockRecorder
}

// MockIContactsRemoteMockRecorder is the mock recorder for MockIContactsRemote.
type MockIContactsRemoteMockRecorder struct {
	mock *MockIContactsRemote
}

// NewMockIContactsRemote creates a new mock instance.
func NewMockIContactsRemote(ctrl *gomock.Controller) *MockIContactsRemote {
	mock := &MockIContactsRemote{ctrl: ctrl}
	mock.recorder = &MockIContactsRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactsRemote) EXPECT() *MockIContactsRemoteMockRecorder {
	return m.recorder
}

// DeleteUsersDataInContacts mocks base method.
func (m *MockIContactsRemote) DeleteUsersDataInContacts(ctx context.Context, usersIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsersDataInContacts", ctx, usersIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsersDataInContacts indicates an expected call of DeleteUsersDataInContacts.
func (mr *MockIContactsRemoteMockRecorder) DeleteUsersDataInContacts(ctx, usersIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsersDataInContacts", reflect.TypeOf((*MockIContactsRemote)(nil).DeleteUsersDataInContacts), ctx, usersIDs)
}

// GetIncomingRelations mocks base method.
func (m *MockIContactsRemote) GetIncomingRelations(ctx context.Context, userIDs []int64) (map[int64]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingRelations", ctx, userIDs)
	ret0, _ := ret[0].(map[int64]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingRelations indicates an expected call of GetIncomingRelations.
func (mr *MockIContactsRemoteMockRecorder) GetIncomingRelations(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingRelations", reflect.TypeOf((*MockIContactsRemote)(nil).GetIncomingRelations), ctx, userIDs)
}
