// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/credentials.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/iam/ent"
	struc "gitlab.calendaria.team/services/utils/v2/struc"
	oauth2 "golang.org/x/oauth2"
)

// MockCredentialsRepo is a mock of CredentialsRepo interface.
type MockCredentialsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepoMockRecorder
}

// MockCredentialsRepoMockRecorder is the mock recorder for MockCredentialsRepo.
type MockCredentialsRepoMockRecorder struct {
	mock *MockCredentialsRepo
}

// NewMockCredentialsRepo creates a new mock instance.
func NewMockCredentialsRepo(ctrl *gomock.Controller) *MockCredentialsRepo {
	mock := &MockCredentialsRepo{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepo) EXPECT() *MockCredentialsRepoMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockCredentialsRepo) CreateCredential(ctx context.Context, actorId int64, token *oauth2.Token) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, actorId, token)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockCredentialsRepoMockRecorder) CreateCredential(ctx, actorId, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).CreateCredential), ctx, actorId, token)
}

// DeleteCredential mocks base method.
func (m *MockCredentialsRepo) DeleteCredential(ctx context.Context, userId, credentialId int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, userId, credentialId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockCredentialsRepoMockRecorder) DeleteCredential(ctx, userId, credentialId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).DeleteCredential), ctx, userId, credentialId)
}

// GetCredential mocks base method.
func (m *MockCredentialsRepo) GetCredential(ctx context.Context, userId int64, provider struc.Provider) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential", ctx, userId, provider)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockCredentialsRepoMockRecorder) GetCredential(ctx, userId, provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).GetCredential), ctx, userId, provider)
}

// ListCredentials mocks base method.
func (m *MockCredentialsRepo) ListCredentials(ctx context.Context, userId int64) ([]*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx, userId)
	ret0, _ := ret[0].([]*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockCredentialsRepoMockRecorder) ListCredentials(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockCredentialsRepo)(nil).ListCredentials), ctx, userId)
}
