// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/credentials.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "github.com/makesalekz/iam/ent"
	integration "github.com/makesalekz/iam/internal/data/integration"
	struc "github.com/makesalekz/utils/v2/struc"
)

// MockCredentialsRepo is a mock of CredentialsRepo interface.
type MockCredentialsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepoMockRecorder
}

// MockCredentialsRepoMockRecorder is the mock recorder for MockCredentialsRepo.
type MockCredentialsRepoMockRecorder struct {
	mock *MockCredentialsRepo
}

// NewMockCredentialsRepo creates a new mock instance.
func NewMockCredentialsRepo(ctrl *gomock.Controller) *MockCredentialsRepo {
	mock := &MockCredentialsRepo{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepo) EXPECT() *MockCredentialsRepoMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockCredentialsRepo) CreateCredential(ctx context.Context, dto integration.CredentialDto) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, dto)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockCredentialsRepoMockRecorder) CreateCredential(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).CreateCredential), ctx, dto)
}

// DeleteCredential mocks base method.
func (m *MockCredentialsRepo) DeleteCredential(ctx context.Context, userID, credentialID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, userID, credentialID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockCredentialsRepoMockRecorder) DeleteCredential(ctx, userID, credentialID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).DeleteCredential), ctx, userID, credentialID)
}

// GetCredential mocks base method.
func (m *MockCredentialsRepo) GetCredential(ctx context.Context, userID, credentialID int64) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential", ctx, userID, credentialID)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockCredentialsRepoMockRecorder) GetCredential(ctx, userID, credentialID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).GetCredential), ctx, userID, credentialID)
}

// GetCredentialByMail mocks base method.
func (m *MockCredentialsRepo) GetCredentialByMail(ctx context.Context, mail string, provider struc.Provider) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByMail", ctx, mail, provider)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByMail indicates an expected call of GetCredentialByMail.
func (mr *MockCredentialsRepoMockRecorder) GetCredentialByMail(ctx, mail, provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByMail", reflect.TypeOf((*MockCredentialsRepo)(nil).GetCredentialByMail), ctx, mail, provider)
}

// GetCredentialByProvider mocks base method.
func (m *MockCredentialsRepo) GetCredentialByProvider(ctx context.Context, userID int64, provider struc.Provider) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByProvider", ctx, userID, provider)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByProvider indicates an expected call of GetCredentialByProvider.
func (mr *MockCredentialsRepoMockRecorder) GetCredentialByProvider(ctx, userID, provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByProvider", reflect.TypeOf((*MockCredentialsRepo)(nil).GetCredentialByProvider), ctx, userID, provider)
}

// ListCredentials mocks base method.
func (m *MockCredentialsRepo) ListCredentials(ctx context.Context, userID int64, provider *struc.Provider) ([]*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx, userID, provider)
	ret0, _ := ret[0].([]*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockCredentialsRepoMockRecorder) ListCredentials(ctx, userID, provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockCredentialsRepo)(nil).ListCredentials), ctx, userID, provider)
}

// UpdateCredential mocks base method.
func (m *MockCredentialsRepo) UpdateCredential(ctx context.Context, credentialID int64, dto integration.CredentialDto) (*ent.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", ctx, credentialID, dto)
	ret0, _ := ret[0].(*ent.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockCredentialsRepoMockRecorder) UpdateCredential(ctx, credentialID, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredential", reflect.TypeOf((*MockCredentialsRepo)(nil).UpdateCredential), ctx, credentialID, dto)
}
