// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/dialer/media.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIMediaRemote is a mock of IMediaRemote interface.
type MockIMediaRemote struct {
	ctrl     *gomock.Controller
	recorder *MockIMediaRemoteMockRecorder
}

// MockIMediaRemoteMockRecorder is the mock recorder for MockIMediaRemote.
type MockIMediaRemoteMockRecorder struct {
	mock *MockIMediaRemote
}

// NewMockIMediaRemote creates a new mock instance.
func NewMockIMediaRemote(ctrl *gomock.Controller) *MockIMediaRemote {
	mock := &MockIMediaRemote{ctrl: ctrl}
	mock.recorder = &MockIMediaRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMediaRemote) EXPECT() *MockIMediaRemoteMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockIMediaRemote) DeleteAvatar(ctx context.Context, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockIMediaRemoteMockRecorder) DeleteAvatar(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockIMediaRemote)(nil).DeleteAvatar), ctx, urls)
}
