// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/integration/provider_gateway.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/iam/ent"
	integration "gitlab.calendaria.team/services/iam/internal/data/integration"
)

// MockIProviderGateway is a mock of IProviderGateway interface.
type MockIProviderGateway struct {
	ctrl     *gomock.Controller
	recorder *MockIProviderGatewayMockRecorder
}

// MockIProviderGatewayMockRecorder is the mock recorder for MockIProviderGateway.
type MockIProviderGatewayMockRecorder struct {
	mock *MockIProviderGateway
}

// NewMockIProviderGateway creates a new mock instance.
func NewMockIProviderGateway(ctrl *gomock.Controller) *MockIProviderGateway {
	mock := &MockIProviderGateway{ctrl: ctrl}
	mock.recorder = &MockIProviderGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProviderGateway) EXPECT() *MockIProviderGatewayMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockIProviderGateway) Authenticate(actorID int64, authCode string) (*integration.CredentialDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", actorID, authCode)
	ret0, _ := ret[0].(*integration.CredentialDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockIProviderGatewayMockRecorder) Authenticate(actorID, authCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockIProviderGateway)(nil).Authenticate), actorID, authCode)
}

// RefreshToken mocks base method.
func (m *MockIProviderGateway) RefreshToken(credential *ent.UserCredentials) (*integration.CredentialDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", credential)
	ret0, _ := ret[0].(*integration.CredentialDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIProviderGatewayMockRecorder) RefreshToken(credential interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIProviderGateway)(nil).RefreshToken), credential)
}

// RevokeToken mocks base method.
func (m *MockIProviderGateway) RevokeToken(credential *ent.UserCredentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockIProviderGatewayMockRecorder) RevokeToken(credential interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockIProviderGateway)(nil).RevokeToken), credential)
}
