// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/integration/provider_manager.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	integration "gitlab.calendaria.team/services/iam/internal/data/integration"
	struc "gitlab.calendaria.team/services/utils/v2/struc"
)

// MockIProviderManager is a mock of IProviderManager interface.
type MockIProviderManager struct {
	ctrl     *gomock.Controller
	recorder *MockIProviderManagerMockRecorder
}

// MockIProviderManagerMockRecorder is the mock recorder for MockIProviderManager.
type MockIProviderManagerMockRecorder struct {
	mock *MockIProviderManager
}

// NewMockIProviderManager creates a new mock instance.
func NewMockIProviderManager(ctrl *gomock.Controller) *MockIProviderManager {
	mock := &MockIProviderManager{ctrl: ctrl}
	mock.recorder = &MockIProviderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProviderManager) EXPECT() *MockIProviderManagerMockRecorder {
	return m.recorder
}

// NewProviderGateway mocks base method.
func (m *MockIProviderManager) NewProviderGateway(provider struc.Provider) (integration.IProviderGateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewProviderGateway", provider)
	ret0, _ := ret[0].(integration.IProviderGateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewProviderGateway indicates an expected call of NewProviderGateway.
func (mr *MockIProviderManagerMockRecorder) NewProviderGateway(provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewProviderGateway", reflect.TypeOf((*MockIProviderManager)(nil).NewProviderGateway), provider)
}
