// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/tenant_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tenants_v1 "gitlab.calendaria.team/services/tenants/api/tenants/v1"
)

// MockITenantRemote is a mock of ITenantRemote interface.
type MockITenantRemote struct {
	ctrl     *gomock.Controller
	recorder *MockITenantRemoteMockRecorder
}

// MockITenantRemoteMockRecorder is the mock recorder for MockITenantRemote.
type MockITenantRemoteMockRecorder struct {
	mock *MockITenantRemote
}

// NewMockITenantRemote creates a new mock instance.
func NewMockITenantRemote(ctrl *gomock.Controller) *MockITenantRemote {
	mock := &MockITenantRemote{ctrl: ctrl}
	mock.recorder = &MockITenantRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITenantRemote) EXPECT() *MockITenantRemoteMockRecorder {
	return m.recorder
}

// CreateTenants mocks base method.
func (m *MockITenantRemote) CreateTenants(ctx context.Context, name string) (*tenants_v1.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenants", ctx, name)
	ret0, _ := ret[0].(*tenants_v1.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenants indicates an expected call of CreateTenants.
func (mr *MockITenantRemoteMockRecorder) CreateTenants(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenants", reflect.TypeOf((*MockITenantRemote)(nil).CreateTenants), ctx, name)
}

// GetMemberIdentities mocks base method.
func (m *MockITenantRemote) GetMemberIdentities(ctx context.Context, tenantId, userId int64) (*tenants_v1.GetMemberIdentitiesReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberIdentities", ctx, tenantId, userId)
	ret0, _ := ret[0].(*tenants_v1.GetMemberIdentitiesReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberIdentities indicates an expected call of GetMemberIdentities.
func (mr *MockITenantRemoteMockRecorder) GetMemberIdentities(ctx, tenantId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberIdentities", reflect.TypeOf((*MockITenantRemote)(nil).GetMemberIdentities), ctx, tenantId, userId)
}

// GetUserTenants mocks base method.
func (m *MockITenantRemote) GetUserTenants(ctx context.Context) ([]*tenants_v1.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTenants", ctx)
	ret0, _ := ret[0].([]*tenants_v1.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTenants indicates an expected call of GetUserTenants.
func (mr *MockITenantRemoteMockRecorder) GetUserTenants(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTenants", reflect.TypeOf((*MockITenantRemote)(nil).GetUserTenants), ctx)
}
