// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/users.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/iam/ent"
	data "gitlab.calendaria.team/services/iam/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockUsersRepo is a mock of UsersRepo interface.
type MockUsersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepoMockRecorder
}

// MockUsersRepoMockRecorder is the mock recorder for MockUsersRepo.
type MockUsersRepoMockRecorder struct {
	mock *MockUsersRepo
}

// NewMockUsersRepo creates a new mock instance.
func NewMockUsersRepo(ctrl *gomock.Controller) *MockUsersRepo {
	mock := &MockUsersRepo{ctrl: ctrl}
	mock.recorder = &MockUsersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepo) EXPECT() *MockUsersRepoMockRecorder {
	return m.recorder
}

// CreateUserWithEmail mocks base method.
func (m *MockUsersRepo) CreateUserWithEmail(ctx context.Context, email string) (*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithEmail", ctx, email)
	ret0, _ := ret[0].(*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWithEmail indicates an expected call of CreateUserWithEmail.
func (mr *MockUsersRepoMockRecorder) CreateUserWithEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithEmail", reflect.TypeOf((*MockUsersRepo)(nil).CreateUserWithEmail), ctx, email)
}

// CreateUserWithPhone mocks base method.
func (m *MockUsersRepo) CreateUserWithPhone(ctx context.Context, phone string) (*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithPhone", ctx, phone)
	ret0, _ := ret[0].(*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWithPhone indicates an expected call of CreateUserWithPhone.
func (mr *MockUsersRepoMockRecorder) CreateUserWithPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithPhone", reflect.TypeOf((*MockUsersRepo)(nil).CreateUserWithPhone), ctx, phone)
}

// DeleteUser mocks base method.
func (m *MockUsersRepo) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersRepoMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersRepo)(nil).DeleteUser), ctx, id)
}

// EmailVerified mocks base method.
func (m *MockUsersRepo) EmailVerified(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailVerified", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmailVerified indicates an expected call of EmailVerified.
func (mr *MockUsersRepoMockRecorder) EmailVerified(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailVerified", reflect.TypeOf((*MockUsersRepo)(nil).EmailVerified), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockUsersRepo) GetUserByEmail(ctx context.Context, email string) (*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUsersRepoMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUsersRepo)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUsersRepo) GetUserByID(ctx context.Context, id int64) (*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUsersRepoMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUsersRepo)(nil).GetUserByID), ctx, id)
}

// GetUserByPhone mocks base method.
func (m *MockUsersRepo) GetUserByPhone(ctx context.Context, phone string) (*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phone)
	ret0, _ := ret[0].(*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockUsersRepoMockRecorder) GetUserByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockUsersRepo)(nil).GetUserByPhone), ctx, phone)
}

// GetUsers mocks base method.
func (m *MockUsersRepo) GetUsers(ctx context.Context, filter data.GetUsersFilterDto) ([]*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, filter)
	ret0, _ := ret[0].([]*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUsersRepoMockRecorder) GetUsers(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUsersRepo)(nil).GetUsers), ctx, filter)
}

// ListUsers mocks base method.
func (m *MockUsersRepo) ListUsers(ctx context.Context, filter data.GetUsersFilterDto, sort *utils_v1.SortRequest, paginate *utils_v1.PaginateRequest) ([]*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, filter, sort, paginate)
	ret0, _ := ret[0].([]*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUsersRepoMockRecorder) ListUsers(ctx, filter, sort, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUsersRepo)(nil).ListUsers), ctx, filter, sort, paginate)
}

// PhoneVerified mocks base method.
func (m *MockUsersRepo) PhoneVerified(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhoneVerified", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PhoneVerified indicates an expected call of PhoneVerified.
func (mr *MockUsersRepoMockRecorder) PhoneVerified(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhoneVerified", reflect.TypeOf((*MockUsersRepo)(nil).PhoneVerified), ctx, userID)
}

// TempGetUsersWithoutDefaultTenant mocks base method.
func (m *MockUsersRepo) TempGetUsersWithoutDefaultTenant(ctx context.Context) ([]*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempGetUsersWithoutDefaultTenant", ctx)
	ret0, _ := ret[0].([]*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempGetUsersWithoutDefaultTenant indicates an expected call of TempGetUsersWithoutDefaultTenant.
func (mr *MockUsersRepoMockRecorder) TempGetUsersWithoutDefaultTenant(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempGetUsersWithoutDefaultTenant", reflect.TypeOf((*MockUsersRepo)(nil).TempGetUsersWithoutDefaultTenant), ctx)
}

// UpdateUserData mocks base method.
func (m *MockUsersRepo) UpdateUserData(ctx context.Context, user *ent.User, dto data.UpdateUserDto) (*ent.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserData", ctx, user, dto)
	ret0, _ := ret[0].(*ent.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserData indicates an expected call of UpdateUserData.
func (mr *MockUsersRepoMockRecorder) UpdateUserData(ctx, user, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserData", reflect.TypeOf((*MockUsersRepo)(nil).UpdateUserData), ctx, user, dto)
}
