// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/remote/websockets.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIWebsocketsRemote is a mock of IWebsocketsRemote interface.
type MockIWebsocketsRemote struct {
	ctrl     *gomock.Controller
	recorder *MockIWebsocketsRemoteMockRecorder
}

// MockIWebsocketsRemoteMockRecorder is the mock recorder for MockIWebsocketsRemote.
type MockIWebsocketsRemoteMockRecorder struct {
	mock *MockIWebsocketsRemote
}

// NewMockIWebsocketsRemote creates a new mock instance.
func NewMockIWebsocketsRemote(ctrl *gomock.Controller) *MockIWebsocketsRemote {
	mock := &MockIWebsocketsRemote{ctrl: ctrl}
	mock.recorder = &MockIWebsocketsRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebsocketsRemote) EXPECT() *MockIWebsocketsRemoteMockRecorder {
	return m.recorder
}

// GetUserStatus mocks base method.
func (m *MockIWebsocketsRemote) GetUserStatus(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatus", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatus indicates an expected call of GetUserStatus.
func (mr *MockIWebsocketsRemoteMockRecorder) GetUserStatus(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatus", reflect.TypeOf((*MockIWebsocketsRemote)(nil).GetUserStatus), ctx, userID)
}

// ListUsersStatuses mocks base method.
func (m *MockIWebsocketsRemote) ListUsersStatuses(ctx context.Context, usersIDs []int64) (map[int64]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersStatuses", ctx, usersIDs)
	ret0, _ := ret[0].(map[int64]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersStatuses indicates an expected call of ListUsersStatuses.
func (mr *MockIWebsocketsRemoteMockRecorder) ListUsersStatuses(ctx, usersIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersStatuses", reflect.TypeOf((*MockIWebsocketsRemote)(nil).ListUsersStatuses), ctx, usersIDs)
}
