// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/iam/internal/biz"
	"gitlab.calendaria.team/services/iam/internal/conf"
	"gitlab.calendaria.team/services/iam/internal/data"
	"gitlab.calendaria.team/services/iam/internal/server"
	"gitlab.calendaria.team/services/iam/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v1/nats"
	"gitlab.calendaria.team/services/utils/v2/dialer"
	"gitlab.calendaria.team/services/utils/v2/jwt"
	"gitlab.calendaria.team/services/utils/v2/tracing"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	encodedConn, cleanup, err := data.NewNatsClient(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	iQueueManager := nats.NewQueueManager(configConfig, encodedConn, logger)
	tracer := tracing.NewTracer(configConfig)
	iDialerManager, err := dialer.NewServiceDialerManager(configConfig, tracer, iJwtProcessor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iTenantsRemote, cleanup2, err := data.NewTenantsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
			iNotificationsRemote, err := data.NewNotificationsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	usersRepo := data.NewUsersRepo(dataData)
	otpRepo := data.NewOtpRepo(dataData)
	authUsecase, err := biz.NewAuthUsecase(logger, iJwtProcessor, iQueueManager, iTenantsRemote, iNotificationsRemote, usersRepo, otpRepo)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(authUsecase)
	iContactsRemote, cleanup4, err := data.NewContactsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iChatsRemote, cleanup5, err := data.NewChatsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iEventsRemote, cleanup6, err := data.NewEventsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iMediaRemote, cleanup7, err := data.NewMediaRemote(logger, bootstrap, iDialerManager)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	privacyRepo := data.NewPrivacyRepo(dataData)
	usersUsecase, err := biz.NewUsersUsecase(logger, iJwtProcessor, iQueueManager, iTenantsRemote, iContactsRemote, iChatsRemote, iEventsRemote, iMediaRemote, usersRepo, otpRepo, privacyRepo)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	usersService := service.NewUsersService(logger, usersUsecase)
	privacyUsecase, err := biz.NewPrivacyUsecase(privacyRepo)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	privacyService := service.NewPrivacyService(privacyUsecase)
	settingsRepo := data.NewSettingsRepo(dataData)
	settingsUsecase, err := biz.NewSettingsUsecase(settingsRepo)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	settingsService := service.NewSettingsService(settingsUsecase)
	credentialsRepo := data.NewCredentialsRepo(dataData)
	credentialsUsecase, err := biz.NewCredentialsUsecase(configConfig, logger, iQueueManager, iJwtProcessor, credentialsRepo)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	credentialsService := service.NewCredentialsService(logger, credentialsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, authService, usersService, privacyService, settingsService, credentialsService, tracer)
	httpServer := server.NewHTTPServer(bootstrap)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
