// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/makesalekz/iam/internal/biz"
	"github.com/makesalekz/iam/internal/conf"
	"github.com/makesalekz/iam/internal/data"
	"github.com/makesalekz/iam/internal/data/integration"
	"github.com/makesalekz/iam/internal/data/remote"
	"github.com/makesalekz/iam/internal/server"
	"github.com/makesalekz/iam/internal/service"
	"github.com/makesalekz/utils/v4/config"
	"github.com/makesalekz/utils/v4/dialer"
	"github.com/makesalekz/utils/v4/jwt"
	"github.com/makesalekz/utils/v4/nats"
	"github.com/makesalekz/utils/v4/tracing"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	iConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(iConfig)
	if err != nil {
		return nil, nil, err
	}
	iTracer := tracing.NewTracer(iConfig)
	conn, cleanup, err := data.NewNatsClient(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	iQueueManager := nats.NewQueueManager(iConfig, conn, logger)
	iDialerManager, err := dialer.NewServiceDialerManager(iConfig, iTracer, iJwtProcessor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iTenantsRemote, cleanup2, err := remote.NewTenantsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iNotificationsRemote, err := remote.NewNotificationsRemote(bootstrap, iDialerManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(bootstrap, iConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	usersRepo := data.NewUsersRepo(dataData)
	otpRepo := data.NewOtpRepo(dataData)
	authUsecase, err := biz.NewAuthUsecase(logger, iJwtProcessor, iQueueManager, iTenantsRemote, iNotificationsRemote, usersRepo, otpRepo)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(authUsecase)
	iContactsRemote := remote.NewContactsRemote()
	iChatsRemote := remote.NewChatsRemote()
	iEventsRemote := remote.NewEventsRemote()
	iMediaRemote, cleanup4, err := remote.NewMediaRemote(logger, bootstrap, iDialerManager)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iWebsocketsRemote := remote.NewWebsocketsRemote()
	privacyRepo := data.NewPrivacyRepo(dataData)
	usersUsecase, err := biz.NewUsersUsecase(logger, iJwtProcessor, iQueueManager, iTenantsRemote, iContactsRemote, iChatsRemote, iEventsRemote, iMediaRemote, iWebsocketsRemote, usersRepo, otpRepo, privacyRepo)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	usersService := service.NewUsersService(logger, usersUsecase)
	privacyUsecase, err := biz.NewPrivacyUsecase(privacyRepo)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	privacyService := service.NewPrivacyService(privacyUsecase)
	settingsRepo := data.NewSettingsRepo(dataData)
	settingsUsecase, err := biz.NewSettingsUsecase(settingsRepo)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	settingsService := service.NewSettingsService(settingsUsecase)
	iProviderManager, err := integration.NewProviderManager(iConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	credentialsRepo := data.NewCredentialsRepo(dataData)
	credentialsUsecase, err := biz.NewCredentialsUsecase(iConfig, logger, iQueueManager, iJwtProcessor, iProviderManager, iEventsRemote, credentialsRepo)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	credentialsService := service.NewCredentialsService(logger, credentialsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, iTracer, authService, usersService, privacyService, settingsService, credentialsService)
	httpServer := server.NewHTTPServer(bootstrap)
	cronServer := server.NewCronServer(logger, usersUsecase)
	app := newApp(logger, iConfig, grpcServer, httpServer, cronServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
