// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OneTimePasswordsColumns holds the columns for the "one_time_passwords" table.
	OneTimePasswordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Size: 6},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"EMAIL", "PHONE"}},
		{Name: "is_used", Type: field.TypeBool, Default: false},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// OneTimePasswordsTable holds the schema information for the "one_time_passwords" table.
	OneTimePasswordsTable = &schema.Table{
		Name:       "one_time_passwords",
		Columns:    OneTimePasswordsColumns,
		PrimaryKey: []*schema.Column{OneTimePasswordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "one_time_passwords_users_user",
				Columns:    []*schema.Column{OneTimePasswordsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "phone", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "bio", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "last_login_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OneTimePasswordsTable,
		UsersTable,
	}
)

func init() {
	OneTimePasswordsTable.ForeignKeys[0].RefTable = UsersTable
}
