// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/iam/internal/biz"
	"gitlab.calendaria.team/services/iam/internal/conf"
	"gitlab.calendaria.team/services/iam/internal/data"
	"gitlab.calendaria.team/services/iam/internal/server"
	"gitlab.calendaria.team/services/iam/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v1/jwt"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dialer, err := data.NewDialer(configConfig, bootstrap, jwtProcessor)
	if err != nil {
		return nil, nil, err
	}
	tenantsRemote, err := data.NewTenantsRemote(configConfig, bootstrap, jwtProcessor)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := data.NewUsersRepo(dataData, logger)
	otpRepo := data.NewOtpRepo(dataData)
	natsClient, cleanup2, err := data.NewNatsClient(configConfig, bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queueManager := biz.NewQueueManager(configConfig, natsClient, logger)
	authUsecase, err := biz.NewAuthUsecase(logger, jwtProcessor, dialer, tenantsRemote, usersRepo, otpRepo, queueManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(logger, authUsecase)
	usersUsecase, err := biz.NewUsersUsecase(logger, configConfig, jwtProcessor, usersRepo, otpRepo, dialer, tenantsRemote)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	usersService := service.NewUsersService(logger, jwtProcessor, usersUsecase)
	privacyRepo := data.NewPrivacyRepo(dataData)
	privacyUsecase, err := biz.NewPrivacyUsecase(privacyRepo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	privacyService := service.NewPrivacyService(logger, jwtProcessor, privacyUsecase)
	settingsRepo := data.NewSettingsRepo(dataData)
	settingsUsecase, err := biz.NewSettingsUsecase(settingsRepo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	settingsService := service.NewSettingsService(logger, jwtProcessor, settingsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, authService, usersService, privacyService, settingsService)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, authService, usersService, privacyService, settingsService)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
