// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/hashicorp/consul/api"
	"iam/internal/biz"
	"iam/internal/conf"
	"iam/internal/data"
	"iam/internal/server"
	"iam/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, client *api.Client, logger log.Logger) (*kratos.App, func(), error) {
	jwtProcessor, err := biz.NewJwtProcessor()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := data.NewUsersRepo(dataData, logger)
	otpRepo := data.NewOtpRepo(dataData)
	authUsecase, err := biz.NewAuthUsecase(bootstrap, logger, client, usersRepo, otpRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(bootstrap, logger, jwtProcessor, authUsecase)
	usersUsecase, err := biz.NewUsersUsecase(bootstrap, logger, client, usersRepo, otpRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	usersService := service.NewUsersService(logger, jwtProcessor, usersUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, authService, usersService)
	privacyRepo := data.NewPrivacyRepo(dataData)
	privacyUsecase, err := biz.NewPrivacyUsecase(privacyRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	privacyService := service.NewPrivacyService(logger, jwtProcessor, privacyUsecase)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, authService, usersService, privacyService)
	app := newApp(logger, client, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
