// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"gitlab.calendaria.team/services/iam/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.calendaria.team/services/iam/ent/onetimepassword"
	"gitlab.calendaria.team/services/iam/ent/user"
	"gitlab.calendaria.team/services/iam/ent/userprivacy"
	"gitlab.calendaria.team/services/iam/ent/usersettings"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// OneTimePassword is the client for interacting with the OneTimePassword builders.
	OneTimePassword *OneTimePasswordClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserPrivacy is the client for interacting with the UserPrivacy builders.
	UserPrivacy *UserPrivacyClient
	// UserSettings is the client for interacting with the UserSettings builders.
	UserSettings *UserSettingsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.OneTimePassword = NewOneTimePasswordClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserPrivacy = NewUserPrivacyClient(c.config)
	c.UserSettings = NewUserSettingsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		OneTimePassword: NewOneTimePasswordClient(cfg),
		User:            NewUserClient(cfg),
		UserPrivacy:     NewUserPrivacyClient(cfg),
		UserSettings:    NewUserSettingsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		OneTimePassword: NewOneTimePasswordClient(cfg),
		User:            NewUserClient(cfg),
		UserPrivacy:     NewUserPrivacyClient(cfg),
		UserSettings:    NewUserSettingsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		OneTimePassword.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.OneTimePassword.Use(hooks...)
	c.User.Use(hooks...)
	c.UserPrivacy.Use(hooks...)
	c.UserSettings.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.OneTimePassword.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
	c.UserPrivacy.Intercept(interceptors...)
	c.UserSettings.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OneTimePasswordMutation:
		return c.OneTimePassword.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserPrivacyMutation:
		return c.UserPrivacy.mutate(ctx, m)
	case *UserSettingsMutation:
		return c.UserSettings.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// OneTimePasswordClient is a client for the OneTimePassword schema.
type OneTimePasswordClient struct {
	config
}

// NewOneTimePasswordClient returns a client for the OneTimePassword from the given config.
func NewOneTimePasswordClient(c config) *OneTimePasswordClient {
	return &OneTimePasswordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `onetimepassword.Hooks(f(g(h())))`.
func (c *OneTimePasswordClient) Use(hooks ...Hook) {
	c.hooks.OneTimePassword = append(c.hooks.OneTimePassword, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `onetimepassword.Intercept(f(g(h())))`.
func (c *OneTimePasswordClient) Intercept(interceptors ...Interceptor) {
	c.inters.OneTimePassword = append(c.inters.OneTimePassword, interceptors...)
}

// Create returns a builder for creating a OneTimePassword entity.
func (c *OneTimePasswordClient) Create() *OneTimePasswordCreate {
	mutation := newOneTimePasswordMutation(c.config, OpCreate)
	return &OneTimePasswordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OneTimePassword entities.
func (c *OneTimePasswordClient) CreateBulk(builders ...*OneTimePasswordCreate) *OneTimePasswordCreateBulk {
	return &OneTimePasswordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OneTimePasswordClient) MapCreateBulk(slice any, setFunc func(*OneTimePasswordCreate, int)) *OneTimePasswordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OneTimePasswordCreateBulk{err: fmt.Errorf("calling to OneTimePasswordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OneTimePasswordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OneTimePasswordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OneTimePassword.
func (c *OneTimePasswordClient) Update() *OneTimePasswordUpdate {
	mutation := newOneTimePasswordMutation(c.config, OpUpdate)
	return &OneTimePasswordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OneTimePasswordClient) UpdateOne(otp *OneTimePassword) *OneTimePasswordUpdateOne {
	mutation := newOneTimePasswordMutation(c.config, OpUpdateOne, withOneTimePassword(otp))
	return &OneTimePasswordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OneTimePasswordClient) UpdateOneID(id int64) *OneTimePasswordUpdateOne {
	mutation := newOneTimePasswordMutation(c.config, OpUpdateOne, withOneTimePasswordID(id))
	return &OneTimePasswordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OneTimePassword.
func (c *OneTimePasswordClient) Delete() *OneTimePasswordDelete {
	mutation := newOneTimePasswordMutation(c.config, OpDelete)
	return &OneTimePasswordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OneTimePasswordClient) DeleteOne(otp *OneTimePassword) *OneTimePasswordDeleteOne {
	return c.DeleteOneID(otp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OneTimePasswordClient) DeleteOneID(id int64) *OneTimePasswordDeleteOne {
	builder := c.Delete().Where(onetimepassword.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OneTimePasswordDeleteOne{builder}
}

// Query returns a query builder for OneTimePassword.
func (c *OneTimePasswordClient) Query() *OneTimePasswordQuery {
	return &OneTimePasswordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOneTimePassword},
		inters: c.Interceptors(),
	}
}

// Get returns a OneTimePassword entity by its id.
func (c *OneTimePasswordClient) Get(ctx context.Context, id int64) (*OneTimePassword, error) {
	return c.Query().Where(onetimepassword.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OneTimePasswordClient) GetX(ctx context.Context, id int64) *OneTimePassword {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a OneTimePassword.
func (c *OneTimePasswordClient) QueryUser(otp *OneTimePassword) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := otp.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(onetimepassword.Table, onetimepassword.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, onetimepassword.UserTable, onetimepassword.UserColumn),
		)
		fromV = sqlgraph.Neighbors(otp.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OneTimePasswordClient) Hooks() []Hook {
	return c.hooks.OneTimePassword
}

// Interceptors returns the client interceptors.
func (c *OneTimePasswordClient) Interceptors() []Interceptor {
	return c.inters.OneTimePassword
}

func (c *OneTimePasswordClient) mutate(ctx context.Context, m *OneTimePasswordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OneTimePasswordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OneTimePasswordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OneTimePasswordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OneTimePasswordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OneTimePassword mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int64) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int64) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int64) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int64) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	inters := c.inters.User
	return append(inters[:len(inters):len(inters)], user.Interceptors[:]...)
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserPrivacyClient is a client for the UserPrivacy schema.
type UserPrivacyClient struct {
	config
}

// NewUserPrivacyClient returns a client for the UserPrivacy from the given config.
func NewUserPrivacyClient(c config) *UserPrivacyClient {
	return &UserPrivacyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userprivacy.Hooks(f(g(h())))`.
func (c *UserPrivacyClient) Use(hooks ...Hook) {
	c.hooks.UserPrivacy = append(c.hooks.UserPrivacy, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userprivacy.Intercept(f(g(h())))`.
func (c *UserPrivacyClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserPrivacy = append(c.inters.UserPrivacy, interceptors...)
}

// Create returns a builder for creating a UserPrivacy entity.
func (c *UserPrivacyClient) Create() *UserPrivacyCreate {
	mutation := newUserPrivacyMutation(c.config, OpCreate)
	return &UserPrivacyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserPrivacy entities.
func (c *UserPrivacyClient) CreateBulk(builders ...*UserPrivacyCreate) *UserPrivacyCreateBulk {
	return &UserPrivacyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserPrivacyClient) MapCreateBulk(slice any, setFunc func(*UserPrivacyCreate, int)) *UserPrivacyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserPrivacyCreateBulk{err: fmt.Errorf("calling to UserPrivacyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserPrivacyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserPrivacyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserPrivacy.
func (c *UserPrivacyClient) Update() *UserPrivacyUpdate {
	mutation := newUserPrivacyMutation(c.config, OpUpdate)
	return &UserPrivacyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserPrivacyClient) UpdateOne(up *UserPrivacy) *UserPrivacyUpdateOne {
	mutation := newUserPrivacyMutation(c.config, OpUpdateOne, withUserPrivacy(up))
	return &UserPrivacyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserPrivacyClient) UpdateOneID(id int64) *UserPrivacyUpdateOne {
	mutation := newUserPrivacyMutation(c.config, OpUpdateOne, withUserPrivacyID(id))
	return &UserPrivacyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserPrivacy.
func (c *UserPrivacyClient) Delete() *UserPrivacyDelete {
	mutation := newUserPrivacyMutation(c.config, OpDelete)
	return &UserPrivacyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserPrivacyClient) DeleteOne(up *UserPrivacy) *UserPrivacyDeleteOne {
	return c.DeleteOneID(up.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserPrivacyClient) DeleteOneID(id int64) *UserPrivacyDeleteOne {
	builder := c.Delete().Where(userprivacy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserPrivacyDeleteOne{builder}
}

// Query returns a query builder for UserPrivacy.
func (c *UserPrivacyClient) Query() *UserPrivacyQuery {
	return &UserPrivacyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserPrivacy},
		inters: c.Interceptors(),
	}
}

// Get returns a UserPrivacy entity by its id.
func (c *UserPrivacyClient) Get(ctx context.Context, id int64) (*UserPrivacy, error) {
	return c.Query().Where(userprivacy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserPrivacyClient) GetX(ctx context.Context, id int64) *UserPrivacy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserPrivacy.
func (c *UserPrivacyClient) QueryUser(up *UserPrivacy) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := up.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userprivacy.Table, userprivacy.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, userprivacy.UserTable, userprivacy.UserColumn),
		)
		fromV = sqlgraph.Neighbors(up.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserPrivacyClient) Hooks() []Hook {
	return c.hooks.UserPrivacy
}

// Interceptors returns the client interceptors.
func (c *UserPrivacyClient) Interceptors() []Interceptor {
	return c.inters.UserPrivacy
}

func (c *UserPrivacyClient) mutate(ctx context.Context, m *UserPrivacyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserPrivacyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserPrivacyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserPrivacyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserPrivacyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserPrivacy mutation op: %q", m.Op())
	}
}

// UserSettingsClient is a client for the UserSettings schema.
type UserSettingsClient struct {
	config
}

// NewUserSettingsClient returns a client for the UserSettings from the given config.
func NewUserSettingsClient(c config) *UserSettingsClient {
	return &UserSettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usersettings.Hooks(f(g(h())))`.
func (c *UserSettingsClient) Use(hooks ...Hook) {
	c.hooks.UserSettings = append(c.hooks.UserSettings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usersettings.Intercept(f(g(h())))`.
func (c *UserSettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserSettings = append(c.inters.UserSettings, interceptors...)
}

// Create returns a builder for creating a UserSettings entity.
func (c *UserSettingsClient) Create() *UserSettingsCreate {
	mutation := newUserSettingsMutation(c.config, OpCreate)
	return &UserSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserSettings entities.
func (c *UserSettingsClient) CreateBulk(builders ...*UserSettingsCreate) *UserSettingsCreateBulk {
	return &UserSettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserSettingsClient) MapCreateBulk(slice any, setFunc func(*UserSettingsCreate, int)) *UserSettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserSettingsCreateBulk{err: fmt.Errorf("calling to UserSettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserSettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserSettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserSettings.
func (c *UserSettingsClient) Update() *UserSettingsUpdate {
	mutation := newUserSettingsMutation(c.config, OpUpdate)
	return &UserSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserSettingsClient) UpdateOne(us *UserSettings) *UserSettingsUpdateOne {
	mutation := newUserSettingsMutation(c.config, OpUpdateOne, withUserSettings(us))
	return &UserSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserSettingsClient) UpdateOneID(id int64) *UserSettingsUpdateOne {
	mutation := newUserSettingsMutation(c.config, OpUpdateOne, withUserSettingsID(id))
	return &UserSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserSettings.
func (c *UserSettingsClient) Delete() *UserSettingsDelete {
	mutation := newUserSettingsMutation(c.config, OpDelete)
	return &UserSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserSettingsClient) DeleteOne(us *UserSettings) *UserSettingsDeleteOne {
	return c.DeleteOneID(us.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserSettingsClient) DeleteOneID(id int64) *UserSettingsDeleteOne {
	builder := c.Delete().Where(usersettings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserSettingsDeleteOne{builder}
}

// Query returns a query builder for UserSettings.
func (c *UserSettingsClient) Query() *UserSettingsQuery {
	return &UserSettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a UserSettings entity by its id.
func (c *UserSettingsClient) Get(ctx context.Context, id int64) (*UserSettings, error) {
	return c.Query().Where(usersettings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserSettingsClient) GetX(ctx context.Context, id int64) *UserSettings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserSettings.
func (c *UserSettingsClient) QueryUser(us *UserSettings) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := us.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usersettings.Table, usersettings.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usersettings.UserTable, usersettings.UserColumn),
		)
		fromV = sqlgraph.Neighbors(us.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserSettingsClient) Hooks() []Hook {
	return c.hooks.UserSettings
}

// Interceptors returns the client interceptors.
func (c *UserSettingsClient) Interceptors() []Interceptor {
	return c.inters.UserSettings
}

func (c *UserSettingsClient) mutate(ctx context.Context, m *UserSettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserSettings mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		OneTimePassword, User, UserPrivacy, UserSettings []ent.Hook
	}
	inters struct {
		OneTimePassword, User, UserPrivacy, UserSettings []ent.Interceptor
	}
)
