// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.calendaria.team/services/iam/ent/onetimepassword"
	"gitlab.calendaria.team/services/iam/ent/predicate"
	"gitlab.calendaria.team/services/iam/ent/user"
	"gitlab.calendaria.team/services/iam/ent/usercredentials"
	"gitlab.calendaria.team/services/iam/ent/userprivacy"
	"gitlab.calendaria.team/services/iam/ent/usersettings"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 5)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   onetimepassword.Table,
			Columns: onetimepassword.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: onetimepassword.FieldID,
			},
		},
		Type: "OneTimePassword",
		Fields: map[string]*sqlgraph.FieldSpec{
			onetimepassword.FieldUserID:         {Type: field.TypeInt64, Column: onetimepassword.FieldUserID},
			onetimepassword.FieldCode:           {Type: field.TypeString, Column: onetimepassword.FieldCode},
			onetimepassword.FieldType:           {Type: field.TypeEnum, Column: onetimepassword.FieldType},
			onetimepassword.FieldIsUsed:         {Type: field.TypeBool, Column: onetimepassword.FieldIsUsed},
			onetimepassword.FieldExpiresAt:      {Type: field.TypeTime, Column: onetimepassword.FieldExpiresAt},
			onetimepassword.FieldCreatedAt:      {Type: field.TypeTime, Column: onetimepassword.FieldCreatedAt},
			onetimepassword.FieldFailedAttempts: {Type: field.TypeInt64, Column: onetimepassword.FieldFailedAttempts},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: user.FieldID,
			},
		},
		Type: "User",
		Fields: map[string]*sqlgraph.FieldSpec{
			user.FieldDeletedAt:       {Type: field.TypeTime, Column: user.FieldDeletedAt},
			user.FieldRemoveAt:        {Type: field.TypeTime, Column: user.FieldRemoveAt},
			user.FieldPhone:           {Type: field.TypeString, Column: user.FieldPhone},
			user.FieldEmail:           {Type: field.TypeString, Column: user.FieldEmail},
			user.FieldUsername:        {Type: field.TypeString, Column: user.FieldUsername},
			user.FieldName:            {Type: field.TypeString, Column: user.FieldName},
			user.FieldBio:             {Type: field.TypeString, Column: user.FieldBio},
			user.FieldAvatar:          {Type: field.TypeString, Column: user.FieldAvatar},
			user.FieldTimezone:        {Type: field.TypeString, Column: user.FieldTimezone},
			user.FieldIsActive:        {Type: field.TypeBool, Column: user.FieldIsActive},
			user.FieldPhoneVerified:   {Type: field.TypeBool, Column: user.FieldPhoneVerified},
			user.FieldEmailVerified:   {Type: field.TypeBool, Column: user.FieldEmailVerified},
			user.FieldLastLoginAt:     {Type: field.TypeTime, Column: user.FieldLastLoginAt},
			user.FieldCreatedAt:       {Type: field.TypeTime, Column: user.FieldCreatedAt},
			user.FieldUpdatedAt:       {Type: field.TypeTime, Column: user.FieldUpdatedAt},
			user.FieldBioUpdatedAt:    {Type: field.TypeTime, Column: user.FieldBioUpdatedAt},
			user.FieldDefaultTenantID: {Type: field.TypeInt64, Column: user.FieldDefaultTenantID},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   usercredentials.Table,
			Columns: usercredentials.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: usercredentials.FieldID,
			},
		},
		Type: "UserCredentials",
		Fields: map[string]*sqlgraph.FieldSpec{
			usercredentials.FieldDeletedAt:    {Type: field.TypeTime, Column: usercredentials.FieldDeletedAt},
			usercredentials.FieldUserID:       {Type: field.TypeInt64, Column: usercredentials.FieldUserID},
			usercredentials.FieldMail:         {Type: field.TypeString, Column: usercredentials.FieldMail},
			usercredentials.FieldDisplayName:  {Type: field.TypeString, Column: usercredentials.FieldDisplayName},
			usercredentials.FieldProvider:     {Type: field.TypeEnum, Column: usercredentials.FieldProvider},
			usercredentials.FieldAccessToken:  {Type: field.TypeString, Column: usercredentials.FieldAccessToken},
			usercredentials.FieldTokenType:    {Type: field.TypeString, Column: usercredentials.FieldTokenType},
			usercredentials.FieldRefreshToken: {Type: field.TypeString, Column: usercredentials.FieldRefreshToken},
			usercredentials.FieldExpiresAt:    {Type: field.TypeTime, Column: usercredentials.FieldExpiresAt},
			usercredentials.FieldCreatedAt:    {Type: field.TypeTime, Column: usercredentials.FieldCreatedAt},
			usercredentials.FieldUpdatedAt:    {Type: field.TypeTime, Column: usercredentials.FieldUpdatedAt},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   userprivacy.Table,
			Columns: userprivacy.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: userprivacy.FieldID,
			},
		},
		Type: "UserPrivacy",
		Fields: map[string]*sqlgraph.FieldSpec{
			userprivacy.FieldUserID:    {Type: field.TypeInt64, Column: userprivacy.FieldUserID},
			userprivacy.FieldSetting:   {Type: field.TypeEnum, Column: userprivacy.FieldSetting},
			userprivacy.FieldOption:    {Type: field.TypeEnum, Column: userprivacy.FieldOption},
			userprivacy.FieldUpdatedAt: {Type: field.TypeTime, Column: userprivacy.FieldUpdatedAt},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   usersettings.Table,
			Columns: usersettings.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: usersettings.FieldID,
			},
		},
		Type: "UserSettings",
		Fields: map[string]*sqlgraph.FieldSpec{
			usersettings.FieldUserID:    {Type: field.TypeInt64, Column: usersettings.FieldUserID},
			usersettings.FieldSetting:   {Type: field.TypeEnum, Column: usersettings.FieldSetting},
			usersettings.FieldValue:     {Type: field.TypeString, Column: usersettings.FieldValue},
			usersettings.FieldUpdatedAt: {Type: field.TypeTime, Column: usersettings.FieldUpdatedAt},
		},
	}
	graph.MustAddE(
		"user",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
		},
		"OneTimePassword",
		"User",
	)
	graph.MustAddE(
		"user",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercredentials.UserTable,
			Columns: []string{usercredentials.UserColumn},
			Bidi:    false,
		},
		"UserCredentials",
		"User",
	)
	graph.MustAddE(
		"user",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprivacy.UserTable,
			Columns: []string{userprivacy.UserColumn},
			Bidi:    false,
		},
		"UserPrivacy",
		"User",
	)
	graph.MustAddE(
		"user",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
		},
		"UserSettings",
		"User",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (otpq *OneTimePasswordQuery) addPredicate(pred func(s *sql.Selector)) {
	otpq.predicates = append(otpq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OneTimePasswordQuery builder.
func (otpq *OneTimePasswordQuery) Filter() *OneTimePasswordFilter {
	return &OneTimePasswordFilter{config: otpq.config, predicateAdder: otpq}
}

// addPredicate implements the predicateAdder interface.
func (m *OneTimePasswordMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OneTimePasswordMutation builder.
func (m *OneTimePasswordMutation) Filter() *OneTimePasswordFilter {
	return &OneTimePasswordFilter{config: m.config, predicateAdder: m}
}

// OneTimePasswordFilter provides a generic filtering capability at runtime for OneTimePasswordQuery.
type OneTimePasswordFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OneTimePasswordFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *OneTimePasswordFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(onetimepassword.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *OneTimePasswordFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(onetimepassword.FieldUserID))
}

// WhereCode applies the entql string predicate on the code field.
func (f *OneTimePasswordFilter) WhereCode(p entql.StringP) {
	f.Where(p.Field(onetimepassword.FieldCode))
}

// WhereType applies the entql string predicate on the type field.
func (f *OneTimePasswordFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(onetimepassword.FieldType))
}

// WhereIsUsed applies the entql bool predicate on the is_used field.
func (f *OneTimePasswordFilter) WhereIsUsed(p entql.BoolP) {
	f.Where(p.Field(onetimepassword.FieldIsUsed))
}

// WhereExpiresAt applies the entql time.Time predicate on the expires_at field.
func (f *OneTimePasswordFilter) WhereExpiresAt(p entql.TimeP) {
	f.Where(p.Field(onetimepassword.FieldExpiresAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *OneTimePasswordFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(onetimepassword.FieldCreatedAt))
}

// WhereFailedAttempts applies the entql int64 predicate on the failed_attempts field.
func (f *OneTimePasswordFilter) WhereFailedAttempts(p entql.Int64P) {
	f.Where(p.Field(onetimepassword.FieldFailedAttempts))
}

// WhereHasUser applies a predicate to check if query has an edge user.
func (f *OneTimePasswordFilter) WhereHasUser() {
	f.Where(entql.HasEdge("user"))
}

// WhereHasUserWith applies a predicate to check if query has an edge user with a given conditions (other predicates).
func (f *OneTimePasswordFilter) WhereHasUserWith(preds ...predicate.User) {
	f.Where(entql.HasEdgeWith("user", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (uq *UserQuery) addPredicate(pred func(s *sql.Selector)) {
	uq.predicates = append(uq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the UserQuery builder.
func (uq *UserQuery) Filter() *UserFilter {
	return &UserFilter{config: uq.config, predicateAdder: uq}
}

// addPredicate implements the predicateAdder interface.
func (m *UserMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the UserMutation builder.
func (m *UserMutation) Filter() *UserFilter {
	return &UserFilter{config: m.config, predicateAdder: m}
}

// UserFilter provides a generic filtering capability at runtime for UserQuery.
type UserFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *UserFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *UserFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(user.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *UserFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldDeletedAt))
}

// WhereRemoveAt applies the entql time.Time predicate on the remove_at field.
func (f *UserFilter) WhereRemoveAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldRemoveAt))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *UserFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(user.FieldPhone))
}

// WhereEmail applies the entql string predicate on the email field.
func (f *UserFilter) WhereEmail(p entql.StringP) {
	f.Where(p.Field(user.FieldEmail))
}

// WhereUsername applies the entql string predicate on the username field.
func (f *UserFilter) WhereUsername(p entql.StringP) {
	f.Where(p.Field(user.FieldUsername))
}

// WhereName applies the entql string predicate on the name field.
func (f *UserFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(user.FieldName))
}

// WhereBio applies the entql string predicate on the bio field.
func (f *UserFilter) WhereBio(p entql.StringP) {
	f.Where(p.Field(user.FieldBio))
}

// WhereAvatar applies the entql string predicate on the avatar field.
func (f *UserFilter) WhereAvatar(p entql.StringP) {
	f.Where(p.Field(user.FieldAvatar))
}

// WhereTimezone applies the entql string predicate on the timezone field.
func (f *UserFilter) WhereTimezone(p entql.StringP) {
	f.Where(p.Field(user.FieldTimezone))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *UserFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(user.FieldIsActive))
}

// WherePhoneVerified applies the entql bool predicate on the phone_verified field.
func (f *UserFilter) WherePhoneVerified(p entql.BoolP) {
	f.Where(p.Field(user.FieldPhoneVerified))
}

// WhereEmailVerified applies the entql bool predicate on the email_verified field.
func (f *UserFilter) WhereEmailVerified(p entql.BoolP) {
	f.Where(p.Field(user.FieldEmailVerified))
}

// WhereLastLoginAt applies the entql time.Time predicate on the last_login_at field.
func (f *UserFilter) WhereLastLoginAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldLastLoginAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *UserFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *UserFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldUpdatedAt))
}

// WhereBioUpdatedAt applies the entql time.Time predicate on the bio_updated_at field.
func (f *UserFilter) WhereBioUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(user.FieldBioUpdatedAt))
}

// WhereDefaultTenantID applies the entql int64 predicate on the default_tenant_id field.
func (f *UserFilter) WhereDefaultTenantID(p entql.Int64P) {
	f.Where(p.Field(user.FieldDefaultTenantID))
}

// addPredicate implements the predicateAdder interface.
func (ucq *UserCredentialsQuery) addPredicate(pred func(s *sql.Selector)) {
	ucq.predicates = append(ucq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the UserCredentialsQuery builder.
func (ucq *UserCredentialsQuery) Filter() *UserCredentialsFilter {
	return &UserCredentialsFilter{config: ucq.config, predicateAdder: ucq}
}

// addPredicate implements the predicateAdder interface.
func (m *UserCredentialsMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the UserCredentialsMutation builder.
func (m *UserCredentialsMutation) Filter() *UserCredentialsFilter {
	return &UserCredentialsFilter{config: m.config, predicateAdder: m}
}

// UserCredentialsFilter provides a generic filtering capability at runtime for UserCredentialsQuery.
type UserCredentialsFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *UserCredentialsFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *UserCredentialsFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(usercredentials.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *UserCredentialsFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(usercredentials.FieldDeletedAt))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *UserCredentialsFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(usercredentials.FieldUserID))
}

// WhereMail applies the entql string predicate on the mail field.
func (f *UserCredentialsFilter) WhereMail(p entql.StringP) {
	f.Where(p.Field(usercredentials.FieldMail))
}

// WhereDisplayName applies the entql string predicate on the display_name field.
func (f *UserCredentialsFilter) WhereDisplayName(p entql.StringP) {
	f.Where(p.Field(usercredentials.FieldDisplayName))
}

// WhereProvider applies the entql string predicate on the provider field.
func (f *UserCredentialsFilter) WhereProvider(p entql.StringP) {
	f.Where(p.Field(usercredentials.FieldProvider))
}

// WhereAccessToken applies the entql string predicate on the access_token field.
func (f *UserCredentialsFilter) WhereAccessToken(p entql.StringP) {
	f.Where(p.Field(usercredentials.FieldAccessToken))
}

// WhereTokenType applies the entql string predicate on the token_type field.
func (f *UserCredentialsFilter) WhereTokenType(p entql.StringP) {
	f.Where(p.Field(usercredentials.FieldTokenType))
}

// WhereRefreshToken applies the entql string predicate on the refresh_token field.
func (f *UserCredentialsFilter) WhereRefreshToken(p entql.StringP) {
	f.Where(p.Field(usercredentials.FieldRefreshToken))
}

// WhereExpiresAt applies the entql time.Time predicate on the expires_at field.
func (f *UserCredentialsFilter) WhereExpiresAt(p entql.TimeP) {
	f.Where(p.Field(usercredentials.FieldExpiresAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *UserCredentialsFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(usercredentials.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *UserCredentialsFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(usercredentials.FieldUpdatedAt))
}

// WhereHasUser applies a predicate to check if query has an edge user.
func (f *UserCredentialsFilter) WhereHasUser() {
	f.Where(entql.HasEdge("user"))
}

// WhereHasUserWith applies a predicate to check if query has an edge user with a given conditions (other predicates).
func (f *UserCredentialsFilter) WhereHasUserWith(preds ...predicate.User) {
	f.Where(entql.HasEdgeWith("user", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (upq *UserPrivacyQuery) addPredicate(pred func(s *sql.Selector)) {
	upq.predicates = append(upq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the UserPrivacyQuery builder.
func (upq *UserPrivacyQuery) Filter() *UserPrivacyFilter {
	return &UserPrivacyFilter{config: upq.config, predicateAdder: upq}
}

// addPredicate implements the predicateAdder interface.
func (m *UserPrivacyMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the UserPrivacyMutation builder.
func (m *UserPrivacyMutation) Filter() *UserPrivacyFilter {
	return &UserPrivacyFilter{config: m.config, predicateAdder: m}
}

// UserPrivacyFilter provides a generic filtering capability at runtime for UserPrivacyQuery.
type UserPrivacyFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *UserPrivacyFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *UserPrivacyFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(userprivacy.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *UserPrivacyFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(userprivacy.FieldUserID))
}

// WhereSetting applies the entql string predicate on the setting field.
func (f *UserPrivacyFilter) WhereSetting(p entql.StringP) {
	f.Where(p.Field(userprivacy.FieldSetting))
}

// WhereOption applies the entql string predicate on the option field.
func (f *UserPrivacyFilter) WhereOption(p entql.StringP) {
	f.Where(p.Field(userprivacy.FieldOption))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *UserPrivacyFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(userprivacy.FieldUpdatedAt))
}

// WhereHasUser applies a predicate to check if query has an edge user.
func (f *UserPrivacyFilter) WhereHasUser() {
	f.Where(entql.HasEdge("user"))
}

// WhereHasUserWith applies a predicate to check if query has an edge user with a given conditions (other predicates).
func (f *UserPrivacyFilter) WhereHasUserWith(preds ...predicate.User) {
	f.Where(entql.HasEdgeWith("user", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (usq *UserSettingsQuery) addPredicate(pred func(s *sql.Selector)) {
	usq.predicates = append(usq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the UserSettingsQuery builder.
func (usq *UserSettingsQuery) Filter() *UserSettingsFilter {
	return &UserSettingsFilter{config: usq.config, predicateAdder: usq}
}

// addPredicate implements the predicateAdder interface.
func (m *UserSettingsMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the UserSettingsMutation builder.
func (m *UserSettingsMutation) Filter() *UserSettingsFilter {
	return &UserSettingsFilter{config: m.config, predicateAdder: m}
}

// UserSettingsFilter provides a generic filtering capability at runtime for UserSettingsQuery.
type UserSettingsFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *UserSettingsFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *UserSettingsFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(usersettings.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *UserSettingsFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(usersettings.FieldUserID))
}

// WhereSetting applies the entql string predicate on the setting field.
func (f *UserSettingsFilter) WhereSetting(p entql.StringP) {
	f.Where(p.Field(usersettings.FieldSetting))
}

// WhereValue applies the entql string predicate on the value field.
func (f *UserSettingsFilter) WhereValue(p entql.StringP) {
	f.Where(p.Field(usersettings.FieldValue))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *UserSettingsFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(usersettings.FieldUpdatedAt))
}

// WhereHasUser applies a predicate to check if query has an edge user.
func (f *UserSettingsFilter) WhereHasUser() {
	f.Where(entql.HasEdge("user"))
}

// WhereHasUserWith applies a predicate to check if query has an edge user with a given conditions (other predicates).
func (f *UserSettingsFilter) WhereHasUserWith(preds ...predicate.User) {
	f.Where(entql.HasEdgeWith("user", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
