// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/iam/ent/enum"
	"gitlab.calendaria.team/services/iam/ent/onetimepassword"
	"gitlab.calendaria.team/services/iam/ent/predicate"
	"gitlab.calendaria.team/services/iam/ent/user"
)

// OneTimePasswordUpdate is the builder for updating OneTimePassword entities.
type OneTimePasswordUpdate struct {
	config
	hooks     []Hook
	mutation  *OneTimePasswordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OneTimePasswordUpdate builder.
func (otpu *OneTimePasswordUpdate) Where(ps ...predicate.OneTimePassword) *OneTimePasswordUpdate {
	otpu.mutation.Where(ps...)
	return otpu
}

// SetUserID sets the "user_id" field.
func (otpu *OneTimePasswordUpdate) SetUserID(i int64) *OneTimePasswordUpdate {
	otpu.mutation.SetUserID(i)
	return otpu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (otpu *OneTimePasswordUpdate) SetNillableUserID(i *int64) *OneTimePasswordUpdate {
	if i != nil {
		otpu.SetUserID(*i)
	}
	return otpu
}

// SetCode sets the "code" field.
func (otpu *OneTimePasswordUpdate) SetCode(s string) *OneTimePasswordUpdate {
	otpu.mutation.SetCode(s)
	return otpu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (otpu *OneTimePasswordUpdate) SetNillableCode(s *string) *OneTimePasswordUpdate {
	if s != nil {
		otpu.SetCode(*s)
	}
	return otpu
}

// SetType sets the "type" field.
func (otpu *OneTimePasswordUpdate) SetType(etpt enum.OneTimePasswordType) *OneTimePasswordUpdate {
	otpu.mutation.SetType(etpt)
	return otpu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (otpu *OneTimePasswordUpdate) SetNillableType(etpt *enum.OneTimePasswordType) *OneTimePasswordUpdate {
	if etpt != nil {
		otpu.SetType(*etpt)
	}
	return otpu
}

// SetIsUsed sets the "is_used" field.
func (otpu *OneTimePasswordUpdate) SetIsUsed(b bool) *OneTimePasswordUpdate {
	otpu.mutation.SetIsUsed(b)
	return otpu
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (otpu *OneTimePasswordUpdate) SetNillableIsUsed(b *bool) *OneTimePasswordUpdate {
	if b != nil {
		otpu.SetIsUsed(*b)
	}
	return otpu
}

// SetExpiresAt sets the "expires_at" field.
func (otpu *OneTimePasswordUpdate) SetExpiresAt(t time.Time) *OneTimePasswordUpdate {
	otpu.mutation.SetExpiresAt(t)
	return otpu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (otpu *OneTimePasswordUpdate) SetNillableExpiresAt(t *time.Time) *OneTimePasswordUpdate {
	if t != nil {
		otpu.SetExpiresAt(*t)
	}
	return otpu
}

// SetCreatedAt sets the "created_at" field.
func (otpu *OneTimePasswordUpdate) SetCreatedAt(t time.Time) *OneTimePasswordUpdate {
	otpu.mutation.SetCreatedAt(t)
	return otpu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (otpu *OneTimePasswordUpdate) SetNillableCreatedAt(t *time.Time) *OneTimePasswordUpdate {
	if t != nil {
		otpu.SetCreatedAt(*t)
	}
	return otpu
}

// SetUser sets the "user" edge to the User entity.
func (otpu *OneTimePasswordUpdate) SetUser(u *User) *OneTimePasswordUpdate {
	return otpu.SetUserID(u.ID)
}

// Mutation returns the OneTimePasswordMutation object of the builder.
func (otpu *OneTimePasswordUpdate) Mutation() *OneTimePasswordMutation {
	return otpu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (otpu *OneTimePasswordUpdate) ClearUser() *OneTimePasswordUpdate {
	otpu.mutation.ClearUser()
	return otpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (otpu *OneTimePasswordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, otpu.sqlSave, otpu.mutation, otpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (otpu *OneTimePasswordUpdate) SaveX(ctx context.Context) int {
	affected, err := otpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (otpu *OneTimePasswordUpdate) Exec(ctx context.Context) error {
	_, err := otpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpu *OneTimePasswordUpdate) ExecX(ctx context.Context) {
	if err := otpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (otpu *OneTimePasswordUpdate) check() error {
	if v, ok := otpu.mutation.Code(); ok {
		if err := onetimepassword.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.code": %w`, err)}
		}
	}
	if v, ok := otpu.mutation.GetType(); ok {
		if err := onetimepassword.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.type": %w`, err)}
		}
	}
	if _, ok := otpu.mutation.UserID(); otpu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "OneTimePassword.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (otpu *OneTimePasswordUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OneTimePasswordUpdate {
	otpu.modifiers = append(otpu.modifiers, modifiers...)
	return otpu
}

func (otpu *OneTimePasswordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := otpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(onetimepassword.Table, onetimepassword.Columns, sqlgraph.NewFieldSpec(onetimepassword.FieldID, field.TypeInt64))
	if ps := otpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := otpu.mutation.Code(); ok {
		_spec.SetField(onetimepassword.FieldCode, field.TypeString, value)
	}
	if value, ok := otpu.mutation.GetType(); ok {
		_spec.SetField(onetimepassword.FieldType, field.TypeEnum, value)
	}
	if value, ok := otpu.mutation.IsUsed(); ok {
		_spec.SetField(onetimepassword.FieldIsUsed, field.TypeBool, value)
	}
	if value, ok := otpu.mutation.ExpiresAt(); ok {
		_spec.SetField(onetimepassword.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := otpu.mutation.CreatedAt(); ok {
		_spec.SetField(onetimepassword.FieldCreatedAt, field.TypeTime, value)
	}
	if otpu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := otpu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(otpu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, otpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onetimepassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	otpu.mutation.done = true
	return n, nil
}

// OneTimePasswordUpdateOne is the builder for updating a single OneTimePassword entity.
type OneTimePasswordUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OneTimePasswordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (otpuo *OneTimePasswordUpdateOne) SetUserID(i int64) *OneTimePasswordUpdateOne {
	otpuo.mutation.SetUserID(i)
	return otpuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (otpuo *OneTimePasswordUpdateOne) SetNillableUserID(i *int64) *OneTimePasswordUpdateOne {
	if i != nil {
		otpuo.SetUserID(*i)
	}
	return otpuo
}

// SetCode sets the "code" field.
func (otpuo *OneTimePasswordUpdateOne) SetCode(s string) *OneTimePasswordUpdateOne {
	otpuo.mutation.SetCode(s)
	return otpuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (otpuo *OneTimePasswordUpdateOne) SetNillableCode(s *string) *OneTimePasswordUpdateOne {
	if s != nil {
		otpuo.SetCode(*s)
	}
	return otpuo
}

// SetType sets the "type" field.
func (otpuo *OneTimePasswordUpdateOne) SetType(etpt enum.OneTimePasswordType) *OneTimePasswordUpdateOne {
	otpuo.mutation.SetType(etpt)
	return otpuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (otpuo *OneTimePasswordUpdateOne) SetNillableType(etpt *enum.OneTimePasswordType) *OneTimePasswordUpdateOne {
	if etpt != nil {
		otpuo.SetType(*etpt)
	}
	return otpuo
}

// SetIsUsed sets the "is_used" field.
func (otpuo *OneTimePasswordUpdateOne) SetIsUsed(b bool) *OneTimePasswordUpdateOne {
	otpuo.mutation.SetIsUsed(b)
	return otpuo
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (otpuo *OneTimePasswordUpdateOne) SetNillableIsUsed(b *bool) *OneTimePasswordUpdateOne {
	if b != nil {
		otpuo.SetIsUsed(*b)
	}
	return otpuo
}

// SetExpiresAt sets the "expires_at" field.
func (otpuo *OneTimePasswordUpdateOne) SetExpiresAt(t time.Time) *OneTimePasswordUpdateOne {
	otpuo.mutation.SetExpiresAt(t)
	return otpuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (otpuo *OneTimePasswordUpdateOne) SetNillableExpiresAt(t *time.Time) *OneTimePasswordUpdateOne {
	if t != nil {
		otpuo.SetExpiresAt(*t)
	}
	return otpuo
}

// SetCreatedAt sets the "created_at" field.
func (otpuo *OneTimePasswordUpdateOne) SetCreatedAt(t time.Time) *OneTimePasswordUpdateOne {
	otpuo.mutation.SetCreatedAt(t)
	return otpuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (otpuo *OneTimePasswordUpdateOne) SetNillableCreatedAt(t *time.Time) *OneTimePasswordUpdateOne {
	if t != nil {
		otpuo.SetCreatedAt(*t)
	}
	return otpuo
}

// SetUser sets the "user" edge to the User entity.
func (otpuo *OneTimePasswordUpdateOne) SetUser(u *User) *OneTimePasswordUpdateOne {
	return otpuo.SetUserID(u.ID)
}

// Mutation returns the OneTimePasswordMutation object of the builder.
func (otpuo *OneTimePasswordUpdateOne) Mutation() *OneTimePasswordMutation {
	return otpuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (otpuo *OneTimePasswordUpdateOne) ClearUser() *OneTimePasswordUpdateOne {
	otpuo.mutation.ClearUser()
	return otpuo
}

// Where appends a list predicates to the OneTimePasswordUpdate builder.
func (otpuo *OneTimePasswordUpdateOne) Where(ps ...predicate.OneTimePassword) *OneTimePasswordUpdateOne {
	otpuo.mutation.Where(ps...)
	return otpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (otpuo *OneTimePasswordUpdateOne) Select(field string, fields ...string) *OneTimePasswordUpdateOne {
	otpuo.fields = append([]string{field}, fields...)
	return otpuo
}

// Save executes the query and returns the updated OneTimePassword entity.
func (otpuo *OneTimePasswordUpdateOne) Save(ctx context.Context) (*OneTimePassword, error) {
	return withHooks(ctx, otpuo.sqlSave, otpuo.mutation, otpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (otpuo *OneTimePasswordUpdateOne) SaveX(ctx context.Context) *OneTimePassword {
	node, err := otpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (otpuo *OneTimePasswordUpdateOne) Exec(ctx context.Context) error {
	_, err := otpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpuo *OneTimePasswordUpdateOne) ExecX(ctx context.Context) {
	if err := otpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (otpuo *OneTimePasswordUpdateOne) check() error {
	if v, ok := otpuo.mutation.Code(); ok {
		if err := onetimepassword.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.code": %w`, err)}
		}
	}
	if v, ok := otpuo.mutation.GetType(); ok {
		if err := onetimepassword.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.type": %w`, err)}
		}
	}
	if _, ok := otpuo.mutation.UserID(); otpuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "OneTimePassword.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (otpuo *OneTimePasswordUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OneTimePasswordUpdateOne {
	otpuo.modifiers = append(otpuo.modifiers, modifiers...)
	return otpuo
}

func (otpuo *OneTimePasswordUpdateOne) sqlSave(ctx context.Context) (_node *OneTimePassword, err error) {
	if err := otpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onetimepassword.Table, onetimepassword.Columns, sqlgraph.NewFieldSpec(onetimepassword.FieldID, field.TypeInt64))
	id, ok := otpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OneTimePassword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := otpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onetimepassword.FieldID)
		for _, f := range fields {
			if !onetimepassword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != onetimepassword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := otpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := otpuo.mutation.Code(); ok {
		_spec.SetField(onetimepassword.FieldCode, field.TypeString, value)
	}
	if value, ok := otpuo.mutation.GetType(); ok {
		_spec.SetField(onetimepassword.FieldType, field.TypeEnum, value)
	}
	if value, ok := otpuo.mutation.IsUsed(); ok {
		_spec.SetField(onetimepassword.FieldIsUsed, field.TypeBool, value)
	}
	if value, ok := otpuo.mutation.ExpiresAt(); ok {
		_spec.SetField(onetimepassword.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := otpuo.mutation.CreatedAt(); ok {
		_spec.SetField(onetimepassword.FieldCreatedAt, field.TypeTime, value)
	}
	if otpuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := otpuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(otpuo.modifiers...)
	_node = &OneTimePassword{config: otpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, otpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onetimepassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	otpuo.mutation.done = true
	return _node, nil
}
