// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/iam/ent/enum"
	"gitlab.calendaria.team/services/iam/ent/onetimepassword"
	"gitlab.calendaria.team/services/iam/ent/user"
)

// OneTimePasswordCreate is the builder for creating a OneTimePassword entity.
type OneTimePasswordCreate struct {
	config
	mutation *OneTimePasswordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (otpc *OneTimePasswordCreate) SetUserID(i int64) *OneTimePasswordCreate {
	otpc.mutation.SetUserID(i)
	return otpc
}

// SetCode sets the "code" field.
func (otpc *OneTimePasswordCreate) SetCode(s string) *OneTimePasswordCreate {
	otpc.mutation.SetCode(s)
	return otpc
}

// SetType sets the "type" field.
func (otpc *OneTimePasswordCreate) SetType(etpt enum.OneTimePasswordType) *OneTimePasswordCreate {
	otpc.mutation.SetType(etpt)
	return otpc
}

// SetIsUsed sets the "is_used" field.
func (otpc *OneTimePasswordCreate) SetIsUsed(b bool) *OneTimePasswordCreate {
	otpc.mutation.SetIsUsed(b)
	return otpc
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (otpc *OneTimePasswordCreate) SetNillableIsUsed(b *bool) *OneTimePasswordCreate {
	if b != nil {
		otpc.SetIsUsed(*b)
	}
	return otpc
}

// SetExpiresAt sets the "expires_at" field.
func (otpc *OneTimePasswordCreate) SetExpiresAt(t time.Time) *OneTimePasswordCreate {
	otpc.mutation.SetExpiresAt(t)
	return otpc
}

// SetCreatedAt sets the "created_at" field.
func (otpc *OneTimePasswordCreate) SetCreatedAt(t time.Time) *OneTimePasswordCreate {
	otpc.mutation.SetCreatedAt(t)
	return otpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (otpc *OneTimePasswordCreate) SetNillableCreatedAt(t *time.Time) *OneTimePasswordCreate {
	if t != nil {
		otpc.SetCreatedAt(*t)
	}
	return otpc
}

// SetUser sets the "user" edge to the User entity.
func (otpc *OneTimePasswordCreate) SetUser(u *User) *OneTimePasswordCreate {
	return otpc.SetUserID(u.ID)
}

// Mutation returns the OneTimePasswordMutation object of the builder.
func (otpc *OneTimePasswordCreate) Mutation() *OneTimePasswordMutation {
	return otpc.mutation
}

// Save creates the OneTimePassword in the database.
func (otpc *OneTimePasswordCreate) Save(ctx context.Context) (*OneTimePassword, error) {
	otpc.defaults()
	return withHooks(ctx, otpc.sqlSave, otpc.mutation, otpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (otpc *OneTimePasswordCreate) SaveX(ctx context.Context) *OneTimePassword {
	v, err := otpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otpc *OneTimePasswordCreate) Exec(ctx context.Context) error {
	_, err := otpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpc *OneTimePasswordCreate) ExecX(ctx context.Context) {
	if err := otpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (otpc *OneTimePasswordCreate) defaults() {
	if _, ok := otpc.mutation.IsUsed(); !ok {
		v := onetimepassword.DefaultIsUsed
		otpc.mutation.SetIsUsed(v)
	}
	if _, ok := otpc.mutation.CreatedAt(); !ok {
		v := onetimepassword.DefaultCreatedAt()
		otpc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (otpc *OneTimePasswordCreate) check() error {
	if _, ok := otpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OneTimePassword.user_id"`)}
	}
	if _, ok := otpc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "OneTimePassword.code"`)}
	}
	if v, ok := otpc.mutation.Code(); ok {
		if err := onetimepassword.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.code": %w`, err)}
		}
	}
	if _, ok := otpc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "OneTimePassword.type"`)}
	}
	if v, ok := otpc.mutation.GetType(); ok {
		if err := onetimepassword.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.type": %w`, err)}
		}
	}
	if _, ok := otpc.mutation.IsUsed(); !ok {
		return &ValidationError{Name: "is_used", err: errors.New(`ent: missing required field "OneTimePassword.is_used"`)}
	}
	if _, ok := otpc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OneTimePassword.expires_at"`)}
	}
	if _, ok := otpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OneTimePassword.created_at"`)}
	}
	if _, ok := otpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OneTimePassword.user"`)}
	}
	return nil
}

func (otpc *OneTimePasswordCreate) sqlSave(ctx context.Context) (*OneTimePassword, error) {
	if err := otpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := otpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, otpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	otpc.mutation.id = &_node.ID
	otpc.mutation.done = true
	return _node, nil
}

func (otpc *OneTimePasswordCreate) createSpec() (*OneTimePassword, *sqlgraph.CreateSpec) {
	var (
		_node = &OneTimePassword{config: otpc.config}
		_spec = sqlgraph.NewCreateSpec(onetimepassword.Table, sqlgraph.NewFieldSpec(onetimepassword.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = otpc.conflict
	if value, ok := otpc.mutation.Code(); ok {
		_spec.SetField(onetimepassword.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := otpc.mutation.GetType(); ok {
		_spec.SetField(onetimepassword.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := otpc.mutation.IsUsed(); ok {
		_spec.SetField(onetimepassword.FieldIsUsed, field.TypeBool, value)
		_node.IsUsed = value
	}
	if value, ok := otpc.mutation.ExpiresAt(); ok {
		_spec.SetField(onetimepassword.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := otpc.mutation.CreatedAt(); ok {
		_spec.SetField(onetimepassword.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := otpc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OneTimePassword.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OneTimePasswordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (otpc *OneTimePasswordCreate) OnConflict(opts ...sql.ConflictOption) *OneTimePasswordUpsertOne {
	otpc.conflict = opts
	return &OneTimePasswordUpsertOne{
		create: otpc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OneTimePassword.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (otpc *OneTimePasswordCreate) OnConflictColumns(columns ...string) *OneTimePasswordUpsertOne {
	otpc.conflict = append(otpc.conflict, sql.ConflictColumns(columns...))
	return &OneTimePasswordUpsertOne{
		create: otpc,
	}
}

type (
	// OneTimePasswordUpsertOne is the builder for "upsert"-ing
	//  one OneTimePassword node.
	OneTimePasswordUpsertOne struct {
		create *OneTimePasswordCreate
	}

	// OneTimePasswordUpsert is the "OnConflict" setter.
	OneTimePasswordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *OneTimePasswordUpsert) SetUserID(v int64) *OneTimePasswordUpsert {
	u.Set(onetimepassword.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OneTimePasswordUpsert) UpdateUserID() *OneTimePasswordUpsert {
	u.SetExcluded(onetimepassword.FieldUserID)
	return u
}

// SetCode sets the "code" field.
func (u *OneTimePasswordUpsert) SetCode(v string) *OneTimePasswordUpsert {
	u.Set(onetimepassword.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OneTimePasswordUpsert) UpdateCode() *OneTimePasswordUpsert {
	u.SetExcluded(onetimepassword.FieldCode)
	return u
}

// SetType sets the "type" field.
func (u *OneTimePasswordUpsert) SetType(v enum.OneTimePasswordType) *OneTimePasswordUpsert {
	u.Set(onetimepassword.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *OneTimePasswordUpsert) UpdateType() *OneTimePasswordUpsert {
	u.SetExcluded(onetimepassword.FieldType)
	return u
}

// SetIsUsed sets the "is_used" field.
func (u *OneTimePasswordUpsert) SetIsUsed(v bool) *OneTimePasswordUpsert {
	u.Set(onetimepassword.FieldIsUsed, v)
	return u
}

// UpdateIsUsed sets the "is_used" field to the value that was provided on create.
func (u *OneTimePasswordUpsert) UpdateIsUsed() *OneTimePasswordUpsert {
	u.SetExcluded(onetimepassword.FieldIsUsed)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OneTimePasswordUpsert) SetExpiresAt(v time.Time) *OneTimePasswordUpsert {
	u.Set(onetimepassword.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OneTimePasswordUpsert) UpdateExpiresAt() *OneTimePasswordUpsert {
	u.SetExcluded(onetimepassword.FieldExpiresAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *OneTimePasswordUpsert) SetCreatedAt(v time.Time) *OneTimePasswordUpsert {
	u.Set(onetimepassword.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OneTimePasswordUpsert) UpdateCreatedAt() *OneTimePasswordUpsert {
	u.SetExcluded(onetimepassword.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OneTimePassword.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OneTimePasswordUpsertOne) UpdateNewValues() *OneTimePasswordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OneTimePassword.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OneTimePasswordUpsertOne) Ignore() *OneTimePasswordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OneTimePasswordUpsertOne) DoNothing() *OneTimePasswordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OneTimePasswordCreate.OnConflict
// documentation for more info.
func (u *OneTimePasswordUpsertOne) Update(set func(*OneTimePasswordUpsert)) *OneTimePasswordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OneTimePasswordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *OneTimePasswordUpsertOne) SetUserID(v int64) *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OneTimePasswordUpsertOne) UpdateUserID() *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateUserID()
	})
}

// SetCode sets the "code" field.
func (u *OneTimePasswordUpsertOne) SetCode(v string) *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OneTimePasswordUpsertOne) UpdateCode() *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateCode()
	})
}

// SetType sets the "type" field.
func (u *OneTimePasswordUpsertOne) SetType(v enum.OneTimePasswordType) *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *OneTimePasswordUpsertOne) UpdateType() *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateType()
	})
}

// SetIsUsed sets the "is_used" field.
func (u *OneTimePasswordUpsertOne) SetIsUsed(v bool) *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetIsUsed(v)
	})
}

// UpdateIsUsed sets the "is_used" field to the value that was provided on create.
func (u *OneTimePasswordUpsertOne) UpdateIsUsed() *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateIsUsed()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OneTimePasswordUpsertOne) SetExpiresAt(v time.Time) *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OneTimePasswordUpsertOne) UpdateExpiresAt() *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OneTimePasswordUpsertOne) SetCreatedAt(v time.Time) *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OneTimePasswordUpsertOne) UpdateCreatedAt() *OneTimePasswordUpsertOne {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *OneTimePasswordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OneTimePasswordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OneTimePasswordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OneTimePasswordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OneTimePasswordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OneTimePasswordCreateBulk is the builder for creating many OneTimePassword entities in bulk.
type OneTimePasswordCreateBulk struct {
	config
	err      error
	builders []*OneTimePasswordCreate
	conflict []sql.ConflictOption
}

// Save creates the OneTimePassword entities in the database.
func (otpcb *OneTimePasswordCreateBulk) Save(ctx context.Context) ([]*OneTimePassword, error) {
	if otpcb.err != nil {
		return nil, otpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(otpcb.builders))
	nodes := make([]*OneTimePassword, len(otpcb.builders))
	mutators := make([]Mutator, len(otpcb.builders))
	for i := range otpcb.builders {
		func(i int, root context.Context) {
			builder := otpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OneTimePasswordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, otpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = otpcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, otpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, otpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (otpcb *OneTimePasswordCreateBulk) SaveX(ctx context.Context) []*OneTimePassword {
	v, err := otpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otpcb *OneTimePasswordCreateBulk) Exec(ctx context.Context) error {
	_, err := otpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpcb *OneTimePasswordCreateBulk) ExecX(ctx context.Context) {
	if err := otpcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OneTimePassword.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OneTimePasswordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (otpcb *OneTimePasswordCreateBulk) OnConflict(opts ...sql.ConflictOption) *OneTimePasswordUpsertBulk {
	otpcb.conflict = opts
	return &OneTimePasswordUpsertBulk{
		create: otpcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OneTimePassword.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (otpcb *OneTimePasswordCreateBulk) OnConflictColumns(columns ...string) *OneTimePasswordUpsertBulk {
	otpcb.conflict = append(otpcb.conflict, sql.ConflictColumns(columns...))
	return &OneTimePasswordUpsertBulk{
		create: otpcb,
	}
}

// OneTimePasswordUpsertBulk is the builder for "upsert"-ing
// a bulk of OneTimePassword nodes.
type OneTimePasswordUpsertBulk struct {
	create *OneTimePasswordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OneTimePassword.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OneTimePasswordUpsertBulk) UpdateNewValues() *OneTimePasswordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OneTimePassword.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OneTimePasswordUpsertBulk) Ignore() *OneTimePasswordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OneTimePasswordUpsertBulk) DoNothing() *OneTimePasswordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OneTimePasswordCreateBulk.OnConflict
// documentation for more info.
func (u *OneTimePasswordUpsertBulk) Update(set func(*OneTimePasswordUpsert)) *OneTimePasswordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OneTimePasswordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *OneTimePasswordUpsertBulk) SetUserID(v int64) *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OneTimePasswordUpsertBulk) UpdateUserID() *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateUserID()
	})
}

// SetCode sets the "code" field.
func (u *OneTimePasswordUpsertBulk) SetCode(v string) *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OneTimePasswordUpsertBulk) UpdateCode() *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateCode()
	})
}

// SetType sets the "type" field.
func (u *OneTimePasswordUpsertBulk) SetType(v enum.OneTimePasswordType) *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *OneTimePasswordUpsertBulk) UpdateType() *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateType()
	})
}

// SetIsUsed sets the "is_used" field.
func (u *OneTimePasswordUpsertBulk) SetIsUsed(v bool) *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetIsUsed(v)
	})
}

// UpdateIsUsed sets the "is_used" field to the value that was provided on create.
func (u *OneTimePasswordUpsertBulk) UpdateIsUsed() *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateIsUsed()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OneTimePasswordUpsertBulk) SetExpiresAt(v time.Time) *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OneTimePasswordUpsertBulk) UpdateExpiresAt() *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OneTimePasswordUpsertBulk) SetCreatedAt(v time.Time) *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OneTimePasswordUpsertBulk) UpdateCreatedAt() *OneTimePasswordUpsertBulk {
	return u.Update(func(s *OneTimePasswordUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *OneTimePasswordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OneTimePasswordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OneTimePasswordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OneTimePasswordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
