// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"iam/ent/onetimepassword"
	"iam/ent/property"
	"iam/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OneTimePasswordCreate is the builder for creating a OneTimePassword entity.
type OneTimePasswordCreate struct {
	config
	mutation *OneTimePasswordMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (otpc *OneTimePasswordCreate) SetUserID(i int64) *OneTimePasswordCreate {
	otpc.mutation.SetUserID(i)
	return otpc
}

// SetCode sets the "code" field.
func (otpc *OneTimePasswordCreate) SetCode(s string) *OneTimePasswordCreate {
	otpc.mutation.SetCode(s)
	return otpc
}

// SetType sets the "type" field.
func (otpc *OneTimePasswordCreate) SetType(ptpt property.OneTimePasswordType) *OneTimePasswordCreate {
	otpc.mutation.SetType(ptpt)
	return otpc
}

// SetIsUsed sets the "is_used" field.
func (otpc *OneTimePasswordCreate) SetIsUsed(b bool) *OneTimePasswordCreate {
	otpc.mutation.SetIsUsed(b)
	return otpc
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (otpc *OneTimePasswordCreate) SetNillableIsUsed(b *bool) *OneTimePasswordCreate {
	if b != nil {
		otpc.SetIsUsed(*b)
	}
	return otpc
}

// SetExpiresAt sets the "expires_at" field.
func (otpc *OneTimePasswordCreate) SetExpiresAt(t time.Time) *OneTimePasswordCreate {
	otpc.mutation.SetExpiresAt(t)
	return otpc
}

// SetCreatedAt sets the "created_at" field.
func (otpc *OneTimePasswordCreate) SetCreatedAt(t time.Time) *OneTimePasswordCreate {
	otpc.mutation.SetCreatedAt(t)
	return otpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (otpc *OneTimePasswordCreate) SetNillableCreatedAt(t *time.Time) *OneTimePasswordCreate {
	if t != nil {
		otpc.SetCreatedAt(*t)
	}
	return otpc
}

// SetUser sets the "user" edge to the User entity.
func (otpc *OneTimePasswordCreate) SetUser(u *User) *OneTimePasswordCreate {
	return otpc.SetUserID(u.ID)
}

// Mutation returns the OneTimePasswordMutation object of the builder.
func (otpc *OneTimePasswordCreate) Mutation() *OneTimePasswordMutation {
	return otpc.mutation
}

// Save creates the OneTimePassword in the database.
func (otpc *OneTimePasswordCreate) Save(ctx context.Context) (*OneTimePassword, error) {
	otpc.defaults()
	return withHooks(ctx, otpc.sqlSave, otpc.mutation, otpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (otpc *OneTimePasswordCreate) SaveX(ctx context.Context) *OneTimePassword {
	v, err := otpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otpc *OneTimePasswordCreate) Exec(ctx context.Context) error {
	_, err := otpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpc *OneTimePasswordCreate) ExecX(ctx context.Context) {
	if err := otpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (otpc *OneTimePasswordCreate) defaults() {
	if _, ok := otpc.mutation.IsUsed(); !ok {
		v := onetimepassword.DefaultIsUsed
		otpc.mutation.SetIsUsed(v)
	}
	if _, ok := otpc.mutation.CreatedAt(); !ok {
		v := onetimepassword.DefaultCreatedAt()
		otpc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (otpc *OneTimePasswordCreate) check() error {
	if _, ok := otpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OneTimePassword.user_id"`)}
	}
	if _, ok := otpc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "OneTimePassword.code"`)}
	}
	if v, ok := otpc.mutation.Code(); ok {
		if err := onetimepassword.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.code": %w`, err)}
		}
	}
	if _, ok := otpc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "OneTimePassword.type"`)}
	}
	if v, ok := otpc.mutation.GetType(); ok {
		if err := onetimepassword.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OneTimePassword.type": %w`, err)}
		}
	}
	if _, ok := otpc.mutation.IsUsed(); !ok {
		return &ValidationError{Name: "is_used", err: errors.New(`ent: missing required field "OneTimePassword.is_used"`)}
	}
	if _, ok := otpc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OneTimePassword.expires_at"`)}
	}
	if _, ok := otpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OneTimePassword.created_at"`)}
	}
	if _, ok := otpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OneTimePassword.user"`)}
	}
	return nil
}

func (otpc *OneTimePasswordCreate) sqlSave(ctx context.Context) (*OneTimePassword, error) {
	if err := otpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := otpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, otpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	otpc.mutation.id = &_node.ID
	otpc.mutation.done = true
	return _node, nil
}

func (otpc *OneTimePasswordCreate) createSpec() (*OneTimePassword, *sqlgraph.CreateSpec) {
	var (
		_node = &OneTimePassword{config: otpc.config}
		_spec = sqlgraph.NewCreateSpec(onetimepassword.Table, sqlgraph.NewFieldSpec(onetimepassword.FieldID, field.TypeInt64))
	)
	if value, ok := otpc.mutation.Code(); ok {
		_spec.SetField(onetimepassword.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := otpc.mutation.GetType(); ok {
		_spec.SetField(onetimepassword.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := otpc.mutation.IsUsed(); ok {
		_spec.SetField(onetimepassword.FieldIsUsed, field.TypeBool, value)
		_node.IsUsed = value
	}
	if value, ok := otpc.mutation.ExpiresAt(); ok {
		_spec.SetField(onetimepassword.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := otpc.mutation.CreatedAt(); ok {
		_spec.SetField(onetimepassword.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := otpc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   onetimepassword.UserTable,
			Columns: []string{onetimepassword.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OneTimePasswordCreateBulk is the builder for creating many OneTimePassword entities in bulk.
type OneTimePasswordCreateBulk struct {
	config
	builders []*OneTimePasswordCreate
}

// Save creates the OneTimePassword entities in the database.
func (otpcb *OneTimePasswordCreateBulk) Save(ctx context.Context) ([]*OneTimePassword, error) {
	specs := make([]*sqlgraph.CreateSpec, len(otpcb.builders))
	nodes := make([]*OneTimePassword, len(otpcb.builders))
	mutators := make([]Mutator, len(otpcb.builders))
	for i := range otpcb.builders {
		func(i int, root context.Context) {
			builder := otpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OneTimePasswordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, otpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, otpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, otpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (otpcb *OneTimePasswordCreateBulk) SaveX(ctx context.Context) []*OneTimePassword {
	v, err := otpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otpcb *OneTimePasswordCreateBulk) Exec(ctx context.Context) error {
	_, err := otpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpcb *OneTimePasswordCreateBulk) ExecX(ctx context.Context) {
	if err := otpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
