// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/iam/ent/onetimepassword"
	"gitlab.calendaria.team/services/iam/ent/predicate"
	"gitlab.calendaria.team/services/iam/ent/user"
)

// OneTimePasswordQuery is the builder for querying OneTimePassword entities.
type OneTimePasswordQuery struct {
	config
	ctx        *QueryContext
	order      []onetimepassword.OrderOption
	inters     []Interceptor
	predicates []predicate.OneTimePassword
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OneTimePasswordQuery builder.
func (otpq *OneTimePasswordQuery) Where(ps ...predicate.OneTimePassword) *OneTimePasswordQuery {
	otpq.predicates = append(otpq.predicates, ps...)
	return otpq
}

// Limit the number of records to be returned by this query.
func (otpq *OneTimePasswordQuery) Limit(limit int) *OneTimePasswordQuery {
	otpq.ctx.Limit = &limit
	return otpq
}

// Offset to start from.
func (otpq *OneTimePasswordQuery) Offset(offset int) *OneTimePasswordQuery {
	otpq.ctx.Offset = &offset
	return otpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (otpq *OneTimePasswordQuery) Unique(unique bool) *OneTimePasswordQuery {
	otpq.ctx.Unique = &unique
	return otpq
}

// Order specifies how the records should be ordered.
func (otpq *OneTimePasswordQuery) Order(o ...onetimepassword.OrderOption) *OneTimePasswordQuery {
	otpq.order = append(otpq.order, o...)
	return otpq
}

// QueryUser chains the current query on the "user" edge.
func (otpq *OneTimePasswordQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: otpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := otpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := otpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(onetimepassword.Table, onetimepassword.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, onetimepassword.UserTable, onetimepassword.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(otpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OneTimePassword entity from the query.
// Returns a *NotFoundError when no OneTimePassword was found.
func (otpq *OneTimePasswordQuery) First(ctx context.Context) (*OneTimePassword, error) {
	nodes, err := otpq.Limit(1).All(setContextOp(ctx, otpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{onetimepassword.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) FirstX(ctx context.Context) *OneTimePassword {
	node, err := otpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OneTimePassword ID from the query.
// Returns a *NotFoundError when no OneTimePassword ID was found.
func (otpq *OneTimePasswordQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = otpq.Limit(1).IDs(setContextOp(ctx, otpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{onetimepassword.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) FirstIDX(ctx context.Context) int64 {
	id, err := otpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OneTimePassword entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OneTimePassword entity is found.
// Returns a *NotFoundError when no OneTimePassword entities are found.
func (otpq *OneTimePasswordQuery) Only(ctx context.Context) (*OneTimePassword, error) {
	nodes, err := otpq.Limit(2).All(setContextOp(ctx, otpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{onetimepassword.Label}
	default:
		return nil, &NotSingularError{onetimepassword.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) OnlyX(ctx context.Context) *OneTimePassword {
	node, err := otpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OneTimePassword ID in the query.
// Returns a *NotSingularError when more than one OneTimePassword ID is found.
// Returns a *NotFoundError when no entities are found.
func (otpq *OneTimePasswordQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = otpq.Limit(2).IDs(setContextOp(ctx, otpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{onetimepassword.Label}
	default:
		err = &NotSingularError{onetimepassword.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := otpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OneTimePasswords.
func (otpq *OneTimePasswordQuery) All(ctx context.Context) ([]*OneTimePassword, error) {
	ctx = setContextOp(ctx, otpq.ctx, "All")
	if err := otpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OneTimePassword, *OneTimePasswordQuery]()
	return withInterceptors[[]*OneTimePassword](ctx, otpq, qr, otpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) AllX(ctx context.Context) []*OneTimePassword {
	nodes, err := otpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OneTimePassword IDs.
func (otpq *OneTimePasswordQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if otpq.ctx.Unique == nil && otpq.path != nil {
		otpq.Unique(true)
	}
	ctx = setContextOp(ctx, otpq.ctx, "IDs")
	if err = otpq.Select(onetimepassword.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) IDsX(ctx context.Context) []int64 {
	ids, err := otpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (otpq *OneTimePasswordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, otpq.ctx, "Count")
	if err := otpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, otpq, querierCount[*OneTimePasswordQuery](), otpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) CountX(ctx context.Context) int {
	count, err := otpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (otpq *OneTimePasswordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, otpq.ctx, "Exist")
	switch _, err := otpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (otpq *OneTimePasswordQuery) ExistX(ctx context.Context) bool {
	exist, err := otpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OneTimePasswordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (otpq *OneTimePasswordQuery) Clone() *OneTimePasswordQuery {
	if otpq == nil {
		return nil
	}
	return &OneTimePasswordQuery{
		config:     otpq.config,
		ctx:        otpq.ctx.Clone(),
		order:      append([]onetimepassword.OrderOption{}, otpq.order...),
		inters:     append([]Interceptor{}, otpq.inters...),
		predicates: append([]predicate.OneTimePassword{}, otpq.predicates...),
		withUser:   otpq.withUser.Clone(),
		// clone intermediate query.
		sql:  otpq.sql.Clone(),
		path: otpq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (otpq *OneTimePasswordQuery) WithUser(opts ...func(*UserQuery)) *OneTimePasswordQuery {
	query := (&UserClient{config: otpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	otpq.withUser = query
	return otpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OneTimePassword.Query().
//		GroupBy(onetimepassword.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (otpq *OneTimePasswordQuery) GroupBy(field string, fields ...string) *OneTimePasswordGroupBy {
	otpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OneTimePasswordGroupBy{build: otpq}
	grbuild.flds = &otpq.ctx.Fields
	grbuild.label = onetimepassword.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.OneTimePassword.Query().
//		Select(onetimepassword.FieldUserID).
//		Scan(ctx, &v)
func (otpq *OneTimePasswordQuery) Select(fields ...string) *OneTimePasswordSelect {
	otpq.ctx.Fields = append(otpq.ctx.Fields, fields...)
	sbuild := &OneTimePasswordSelect{OneTimePasswordQuery: otpq}
	sbuild.label = onetimepassword.Label
	sbuild.flds, sbuild.scan = &otpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OneTimePasswordSelect configured with the given aggregations.
func (otpq *OneTimePasswordQuery) Aggregate(fns ...AggregateFunc) *OneTimePasswordSelect {
	return otpq.Select().Aggregate(fns...)
}

func (otpq *OneTimePasswordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range otpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, otpq); err != nil {
				return err
			}
		}
	}
	for _, f := range otpq.ctx.Fields {
		if !onetimepassword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if otpq.path != nil {
		prev, err := otpq.path(ctx)
		if err != nil {
			return err
		}
		otpq.sql = prev
	}
	return nil
}

func (otpq *OneTimePasswordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OneTimePassword, error) {
	var (
		nodes       = []*OneTimePassword{}
		_spec       = otpq.querySpec()
		loadedTypes = [1]bool{
			otpq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OneTimePassword).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OneTimePassword{config: otpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(otpq.modifiers) > 0 {
		_spec.Modifiers = otpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, otpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := otpq.withUser; query != nil {
		if err := otpq.loadUser(ctx, query, nodes, nil,
			func(n *OneTimePassword, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (otpq *OneTimePasswordQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*OneTimePassword, init func(*OneTimePassword), assign func(*OneTimePassword, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OneTimePassword)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (otpq *OneTimePasswordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := otpq.querySpec()
	if len(otpq.modifiers) > 0 {
		_spec.Modifiers = otpq.modifiers
	}
	_spec.Node.Columns = otpq.ctx.Fields
	if len(otpq.ctx.Fields) > 0 {
		_spec.Unique = otpq.ctx.Unique != nil && *otpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, otpq.driver, _spec)
}

func (otpq *OneTimePasswordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(onetimepassword.Table, onetimepassword.Columns, sqlgraph.NewFieldSpec(onetimepassword.FieldID, field.TypeInt64))
	_spec.From = otpq.sql
	if unique := otpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if otpq.path != nil {
		_spec.Unique = true
	}
	if fields := otpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onetimepassword.FieldID)
		for i := range fields {
			if fields[i] != onetimepassword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if otpq.withUser != nil {
			_spec.Node.AddColumnOnce(onetimepassword.FieldUserID)
		}
	}
	if ps := otpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := otpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := otpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := otpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (otpq *OneTimePasswordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(otpq.driver.Dialect())
	t1 := builder.Table(onetimepassword.Table)
	columns := otpq.ctx.Fields
	if len(columns) == 0 {
		columns = onetimepassword.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if otpq.sql != nil {
		selector = otpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if otpq.ctx.Unique != nil && *otpq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range otpq.modifiers {
		m(selector)
	}
	for _, p := range otpq.predicates {
		p(selector)
	}
	for _, p := range otpq.order {
		p(selector)
	}
	if offset := otpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := otpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (otpq *OneTimePasswordQuery) Modify(modifiers ...func(s *sql.Selector)) *OneTimePasswordSelect {
	otpq.modifiers = append(otpq.modifiers, modifiers...)
	return otpq.Select()
}

// OneTimePasswordGroupBy is the group-by builder for OneTimePassword entities.
type OneTimePasswordGroupBy struct {
	selector
	build *OneTimePasswordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (otpgb *OneTimePasswordGroupBy) Aggregate(fns ...AggregateFunc) *OneTimePasswordGroupBy {
	otpgb.fns = append(otpgb.fns, fns...)
	return otpgb
}

// Scan applies the selector query and scans the result into the given value.
func (otpgb *OneTimePasswordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, otpgb.build.ctx, "GroupBy")
	if err := otpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OneTimePasswordQuery, *OneTimePasswordGroupBy](ctx, otpgb.build, otpgb, otpgb.build.inters, v)
}

func (otpgb *OneTimePasswordGroupBy) sqlScan(ctx context.Context, root *OneTimePasswordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(otpgb.fns))
	for _, fn := range otpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*otpgb.flds)+len(otpgb.fns))
		for _, f := range *otpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*otpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := otpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OneTimePasswordSelect is the builder for selecting fields of OneTimePassword entities.
type OneTimePasswordSelect struct {
	*OneTimePasswordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (otps *OneTimePasswordSelect) Aggregate(fns ...AggregateFunc) *OneTimePasswordSelect {
	otps.fns = append(otps.fns, fns...)
	return otps
}

// Scan applies the selector query and scans the result into the given value.
func (otps *OneTimePasswordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, otps.ctx, "Select")
	if err := otps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OneTimePasswordQuery, *OneTimePasswordSelect](ctx, otps.OneTimePasswordQuery, otps, otps.inters, v)
}

func (otps *OneTimePasswordSelect) sqlScan(ctx context.Context, root *OneTimePasswordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(otps.fns))
	for _, fn := range otps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*otps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := otps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (otps *OneTimePasswordSelect) Modify(modifiers ...func(s *sql.Selector)) *OneTimePasswordSelect {
	otps.modifiers = append(otps.modifiers, modifiers...)
	return otps
}
