// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/makesalekz/iam/ent/enum"
	"github.com/makesalekz/iam/ent/onetimepassword"
	"github.com/makesalekz/iam/ent/user"
)

// OneTimePassword is the model entity for the OneTimePassword schema.
type OneTimePassword struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Type holds the value of the "type" field.
	Type enum.OneTimePasswordType `json:"type,omitempty"`
	// IsUsed holds the value of the "is_used" field.
	IsUsed bool `json:"is_used,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// FailedAttempts holds the value of the "failed_attempts" field.
	FailedAttempts int64 `json:"failed_attempts,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OneTimePasswordQuery when eager-loading is set.
	Edges        OneTimePasswordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OneTimePasswordEdges holds the relations/edges for other nodes in the graph.
type OneTimePasswordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OneTimePasswordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OneTimePassword) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case onetimepassword.FieldIsUsed:
			values[i] = new(sql.NullBool)
		case onetimepassword.FieldID, onetimepassword.FieldUserID, onetimepassword.FieldFailedAttempts:
			values[i] = new(sql.NullInt64)
		case onetimepassword.FieldCode, onetimepassword.FieldType:
			values[i] = new(sql.NullString)
		case onetimepassword.FieldExpiresAt, onetimepassword.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OneTimePassword fields.
func (otp *OneTimePassword) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case onetimepassword.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			otp.ID = int64(value.Int64)
		case onetimepassword.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				otp.UserID = value.Int64
			}
		case onetimepassword.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				otp.Code = value.String
			}
		case onetimepassword.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				otp.Type = enum.OneTimePasswordType(value.String)
			}
		case onetimepassword.FieldIsUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_used", values[i])
			} else if value.Valid {
				otp.IsUsed = value.Bool
			}
		case onetimepassword.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				otp.ExpiresAt = value.Time
			}
		case onetimepassword.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				otp.CreatedAt = value.Time
			}
		case onetimepassword.FieldFailedAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_attempts", values[i])
			} else if value.Valid {
				otp.FailedAttempts = value.Int64
			}
		default:
			otp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OneTimePassword.
// This includes values selected through modifiers, order, etc.
func (otp *OneTimePassword) Value(name string) (ent.Value, error) {
	return otp.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OneTimePassword entity.
func (otp *OneTimePassword) QueryUser() *UserQuery {
	return NewOneTimePasswordClient(otp.config).QueryUser(otp)
}

// Update returns a builder for updating this OneTimePassword.
// Note that you need to call OneTimePassword.Unwrap() before calling this method if this OneTimePassword
// was returned from a transaction, and the transaction was committed or rolled back.
func (otp *OneTimePassword) Update() *OneTimePasswordUpdateOne {
	return NewOneTimePasswordClient(otp.config).UpdateOne(otp)
}

// Unwrap unwraps the OneTimePassword entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (otp *OneTimePassword) Unwrap() *OneTimePassword {
	_tx, ok := otp.config.driver.(*txDriver)
	if !ok {
		panic("ent: OneTimePassword is not a transactional entity")
	}
	otp.config.driver = _tx.drv
	return otp
}

// String implements the fmt.Stringer.
func (otp *OneTimePassword) String() string {
	var builder strings.Builder
	builder.WriteString("OneTimePassword(")
	builder.WriteString(fmt.Sprintf("id=%v, ", otp.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", otp.UserID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(otp.Code)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", otp.Type))
	builder.WriteString(", ")
	builder.WriteString("is_used=")
	builder.WriteString(fmt.Sprintf("%v", otp.IsUsed))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(otp.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(otp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("failed_attempts=")
	builder.WriteString(fmt.Sprintf("%v", otp.FailedAttempts))
	builder.WriteByte(')')
	return builder.String()
}

// OneTimePasswords is a parsable slice of OneTimePassword.
type OneTimePasswords []*OneTimePassword
