// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/alageum-cloud/iam/ent/onetimepassword"
	"gitlab.calendaria.team/alageum-cloud/iam/ent/predicate"
)

// OneTimePasswordDelete is the builder for deleting a OneTimePassword entity.
type OneTimePasswordDelete struct {
	config
	hooks    []Hook
	mutation *OneTimePasswordMutation
}

// Where appends a list predicates to the OneTimePasswordDelete builder.
func (otpd *OneTimePasswordDelete) Where(ps ...predicate.OneTimePassword) *OneTimePasswordDelete {
	otpd.mutation.Where(ps...)
	return otpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (otpd *OneTimePasswordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, otpd.sqlExec, otpd.mutation, otpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (otpd *OneTimePasswordDelete) ExecX(ctx context.Context) int {
	n, err := otpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (otpd *OneTimePasswordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(onetimepassword.Table, sqlgraph.NewFieldSpec(onetimepassword.FieldID, field.TypeInt64))
	if ps := otpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, otpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	otpd.mutation.done = true
	return affected, err
}

// OneTimePasswordDeleteOne is the builder for deleting a single OneTimePassword entity.
type OneTimePasswordDeleteOne struct {
	otpd *OneTimePasswordDelete
}

// Where appends a list predicates to the OneTimePasswordDelete builder.
func (otpdo *OneTimePasswordDeleteOne) Where(ps ...predicate.OneTimePassword) *OneTimePasswordDeleteOne {
	otpdo.otpd.mutation.Where(ps...)
	return otpdo
}

// Exec executes the deletion query.
func (otpdo *OneTimePasswordDeleteOne) Exec(ctx context.Context) error {
	n, err := otpdo.otpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{onetimepassword.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (otpdo *OneTimePasswordDeleteOne) ExecX(ctx context.Context) {
	if err := otpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
