// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/iam/ent/enum"
	"gitlab.calendaria.team/services/iam/ent/user"
	"gitlab.calendaria.team/services/iam/ent/usersettings"
)

// UserSettingsCreate is the builder for creating a UserSettings entity.
type UserSettingsCreate struct {
	config
	mutation *UserSettingsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (usc *UserSettingsCreate) SetUserID(i int64) *UserSettingsCreate {
	usc.mutation.SetUserID(i)
	return usc
}

// SetSetting sets the "setting" field.
func (usc *UserSettingsCreate) SetSetting(e enum.Settings) *UserSettingsCreate {
	usc.mutation.SetSetting(e)
	return usc
}

// SetValue sets the "value" field.
func (usc *UserSettingsCreate) SetValue(s string) *UserSettingsCreate {
	usc.mutation.SetValue(s)
	return usc
}

// SetUpdatedAt sets the "updated_at" field.
func (usc *UserSettingsCreate) SetUpdatedAt(t time.Time) *UserSettingsCreate {
	usc.mutation.SetUpdatedAt(t)
	return usc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableUpdatedAt(t *time.Time) *UserSettingsCreate {
	if t != nil {
		usc.SetUpdatedAt(*t)
	}
	return usc
}

// SetUser sets the "user" edge to the User entity.
func (usc *UserSettingsCreate) SetUser(u *User) *UserSettingsCreate {
	return usc.SetUserID(u.ID)
}

// Mutation returns the UserSettingsMutation object of the builder.
func (usc *UserSettingsCreate) Mutation() *UserSettingsMutation {
	return usc.mutation
}

// Save creates the UserSettings in the database.
func (usc *UserSettingsCreate) Save(ctx context.Context) (*UserSettings, error) {
	usc.defaults()
	return withHooks(ctx, usc.sqlSave, usc.mutation, usc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (usc *UserSettingsCreate) SaveX(ctx context.Context) *UserSettings {
	v, err := usc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (usc *UserSettingsCreate) Exec(ctx context.Context) error {
	_, err := usc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usc *UserSettingsCreate) ExecX(ctx context.Context) {
	if err := usc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usc *UserSettingsCreate) defaults() {
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		v := usersettings.DefaultUpdatedAt()
		usc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usc *UserSettingsCreate) check() error {
	if _, ok := usc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserSettings.user_id"`)}
	}
	if _, ok := usc.mutation.Setting(); !ok {
		return &ValidationError{Name: "setting", err: errors.New(`ent: missing required field "UserSettings.setting"`)}
	}
	if v, ok := usc.mutation.Setting(); ok {
		if err := usersettings.SettingValidator(v); err != nil {
			return &ValidationError{Name: "setting", err: fmt.Errorf(`ent: validator failed for field "UserSettings.setting": %w`, err)}
		}
	}
	if _, ok := usc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "UserSettings.value"`)}
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSettings.updated_at"`)}
	}
	if _, ok := usc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserSettings.user"`)}
	}
	return nil
}

func (usc *UserSettingsCreate) sqlSave(ctx context.Context) (*UserSettings, error) {
	if err := usc.check(); err != nil {
		return nil, err
	}
	_node, _spec := usc.createSpec()
	if err := sqlgraph.CreateNode(ctx, usc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	usc.mutation.id = &_node.ID
	usc.mutation.done = true
	return _node, nil
}

func (usc *UserSettingsCreate) createSpec() (*UserSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSettings{config: usc.config}
		_spec = sqlgraph.NewCreateSpec(usersettings.Table, sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = usc.conflict
	if value, ok := usc.mutation.Setting(); ok {
		_spec.SetField(usersettings.FieldSetting, field.TypeEnum, value)
		_node.Setting = value
	}
	if value, ok := usc.mutation.Value(); ok {
		_spec.SetField(usersettings.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := usc.mutation.UpdatedAt(); ok {
		_spec.SetField(usersettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := usc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersettings.UserTable,
			Columns: []string{usersettings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSettings.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSettingsUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (usc *UserSettingsCreate) OnConflict(opts ...sql.ConflictOption) *UserSettingsUpsertOne {
	usc.conflict = opts
	return &UserSettingsUpsertOne{
		create: usc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (usc *UserSettingsCreate) OnConflictColumns(columns ...string) *UserSettingsUpsertOne {
	usc.conflict = append(usc.conflict, sql.ConflictColumns(columns...))
	return &UserSettingsUpsertOne{
		create: usc,
	}
}

type (
	// UserSettingsUpsertOne is the builder for "upsert"-ing
	//  one UserSettings node.
	UserSettingsUpsertOne struct {
		create *UserSettingsCreate
	}

	// UserSettingsUpsert is the "OnConflict" setter.
	UserSettingsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserSettingsUpsert) SetUserID(v int64) *UserSettingsUpsert {
	u.Set(usersettings.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSettingsUpsert) UpdateUserID() *UserSettingsUpsert {
	u.SetExcluded(usersettings.FieldUserID)
	return u
}

// SetSetting sets the "setting" field.
func (u *UserSettingsUpsert) SetSetting(v enum.Settings) *UserSettingsUpsert {
	u.Set(usersettings.FieldSetting, v)
	return u
}

// UpdateSetting sets the "setting" field to the value that was provided on create.
func (u *UserSettingsUpsert) UpdateSetting() *UserSettingsUpsert {
	u.SetExcluded(usersettings.FieldSetting)
	return u
}

// SetValue sets the "value" field.
func (u *UserSettingsUpsert) SetValue(v string) *UserSettingsUpsert {
	u.Set(usersettings.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UserSettingsUpsert) UpdateValue() *UserSettingsUpsert {
	u.SetExcluded(usersettings.FieldValue)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSettingsUpsert) SetUpdatedAt(v time.Time) *UserSettingsUpsert {
	u.Set(usersettings.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSettingsUpsert) UpdateUpdatedAt() *UserSettingsUpsert {
	u.SetExcluded(usersettings.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSettingsUpsertOne) UpdateNewValues() *UserSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSettings.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserSettingsUpsertOne) Ignore() *UserSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSettingsUpsertOne) DoNothing() *UserSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSettingsCreate.OnConflict
// documentation for more info.
func (u *UserSettingsUpsertOne) Update(set func(*UserSettingsUpsert)) *UserSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserSettingsUpsertOne) SetUserID(v int64) *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSettingsUpsertOne) UpdateUserID() *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateUserID()
	})
}

// SetSetting sets the "setting" field.
func (u *UserSettingsUpsertOne) SetSetting(v enum.Settings) *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetSetting(v)
	})
}

// UpdateSetting sets the "setting" field to the value that was provided on create.
func (u *UserSettingsUpsertOne) UpdateSetting() *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateSetting()
	})
}

// SetValue sets the "value" field.
func (u *UserSettingsUpsertOne) SetValue(v string) *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UserSettingsUpsertOne) UpdateValue() *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSettingsUpsertOne) SetUpdatedAt(v time.Time) *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSettingsUpsertOne) UpdateUpdatedAt() *UserSettingsUpsertOne {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserSettingsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSettingsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSettingsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserSettingsUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserSettingsUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserSettingsCreateBulk is the builder for creating many UserSettings entities in bulk.
type UserSettingsCreateBulk struct {
	config
	err      error
	builders []*UserSettingsCreate
	conflict []sql.ConflictOption
}

// Save creates the UserSettings entities in the database.
func (uscb *UserSettingsCreateBulk) Save(ctx context.Context) ([]*UserSettings, error) {
	if uscb.err != nil {
		return nil, uscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uscb.builders))
	nodes := make([]*UserSettings, len(uscb.builders))
	mutators := make([]Mutator, len(uscb.builders))
	for i := range uscb.builders {
		func(i int, root context.Context) {
			builder := uscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = uscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uscb *UserSettingsCreateBulk) SaveX(ctx context.Context) []*UserSettings {
	v, err := uscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uscb *UserSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := uscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uscb *UserSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := uscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSettings.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSettingsUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (uscb *UserSettingsCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserSettingsUpsertBulk {
	uscb.conflict = opts
	return &UserSettingsUpsertBulk{
		create: uscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uscb *UserSettingsCreateBulk) OnConflictColumns(columns ...string) *UserSettingsUpsertBulk {
	uscb.conflict = append(uscb.conflict, sql.ConflictColumns(columns...))
	return &UserSettingsUpsertBulk{
		create: uscb,
	}
}

// UserSettingsUpsertBulk is the builder for "upsert"-ing
// a bulk of UserSettings nodes.
type UserSettingsUpsertBulk struct {
	create *UserSettingsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSettingsUpsertBulk) UpdateNewValues() *UserSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSettings.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserSettingsUpsertBulk) Ignore() *UserSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSettingsUpsertBulk) DoNothing() *UserSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSettingsCreateBulk.OnConflict
// documentation for more info.
func (u *UserSettingsUpsertBulk) Update(set func(*UserSettingsUpsert)) *UserSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserSettingsUpsertBulk) SetUserID(v int64) *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSettingsUpsertBulk) UpdateUserID() *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateUserID()
	})
}

// SetSetting sets the "setting" field.
func (u *UserSettingsUpsertBulk) SetSetting(v enum.Settings) *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetSetting(v)
	})
}

// UpdateSetting sets the "setting" field to the value that was provided on create.
func (u *UserSettingsUpsertBulk) UpdateSetting() *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateSetting()
	})
}

// SetValue sets the "value" field.
func (u *UserSettingsUpsertBulk) SetValue(v string) *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UserSettingsUpsertBulk) UpdateValue() *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSettingsUpsertBulk) SetUpdatedAt(v time.Time) *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSettingsUpsertBulk) UpdateUpdatedAt() *UserSettingsUpsertBulk {
	return u.Update(func(s *UserSettingsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserSettingsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserSettingsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSettingsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSettingsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
