// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/iam/ent/predicate"
	"github.com/makesalekz/iam/ent/usercredentials"
)

// UserCredentialsDelete is the builder for deleting a UserCredentials entity.
type UserCredentialsDelete struct {
	config
	hooks    []Hook
	mutation *UserCredentialsMutation
}

// Where appends a list predicates to the UserCredentialsDelete builder.
func (ucd *UserCredentialsDelete) Where(ps ...predicate.UserCredentials) *UserCredentialsDelete {
	ucd.mutation.Where(ps...)
	return ucd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ucd *UserCredentialsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ucd.sqlExec, ucd.mutation, ucd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ucd *UserCredentialsDelete) ExecX(ctx context.Context) int {
	n, err := ucd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ucd *UserCredentialsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usercredentials.Table, sqlgraph.NewFieldSpec(usercredentials.FieldID, field.TypeInt64))
	if ps := ucd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ucd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ucd.mutation.done = true
	return affected, err
}

// UserCredentialsDeleteOne is the builder for deleting a single UserCredentials entity.
type UserCredentialsDeleteOne struct {
	ucd *UserCredentialsDelete
}

// Where appends a list predicates to the UserCredentialsDelete builder.
func (ucdo *UserCredentialsDeleteOne) Where(ps ...predicate.UserCredentials) *UserCredentialsDeleteOne {
	ucdo.ucd.mutation.Where(ps...)
	return ucdo
}

// Exec executes the deletion query.
func (ucdo *UserCredentialsDeleteOne) Exec(ctx context.Context) error {
	n, err := ucdo.ucd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usercredentials.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ucdo *UserCredentialsDeleteOne) ExecX(ctx context.Context) {
	if err := ucdo.Exec(ctx); err != nil {
		panic(err)
	}
}
