// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/iam/ent/enum"
	"gitlab.calendaria.team/services/iam/ent/user"
	"gitlab.calendaria.team/services/iam/ent/userprivacy"
)

// UserPrivacy is the model entity for the UserPrivacy schema.
type UserPrivacy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Setting holds the value of the "setting" field.
	Setting enum.PrivacySettings `json:"setting,omitempty"`
	// Option holds the value of the "option" field.
	Option enum.PrivacyOptions `json:"option,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserPrivacyQuery when eager-loading is set.
	Edges        UserPrivacyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserPrivacyEdges holds the relations/edges for other nodes in the graph.
type UserPrivacyEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPrivacyEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPrivacy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userprivacy.FieldID, userprivacy.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userprivacy.FieldSetting, userprivacy.FieldOption:
			values[i] = new(sql.NullString)
		case userprivacy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPrivacy fields.
func (up *UserPrivacy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userprivacy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			up.ID = int64(value.Int64)
		case userprivacy.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				up.UserID = value.Int64
			}
		case userprivacy.FieldSetting:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setting", values[i])
			} else if value.Valid {
				up.Setting = enum.PrivacySettings(value.String)
			}
		case userprivacy.FieldOption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field option", values[i])
			} else if value.Valid {
				up.Option = enum.PrivacyOptions(value.String)
			}
		case userprivacy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				up.UpdatedAt = value.Time
			}
		default:
			up.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPrivacy.
// This includes values selected through modifiers, order, etc.
func (up *UserPrivacy) Value(name string) (ent.Value, error) {
	return up.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserPrivacy entity.
func (up *UserPrivacy) QueryUser() *UserQuery {
	return NewUserPrivacyClient(up.config).QueryUser(up)
}

// Update returns a builder for updating this UserPrivacy.
// Note that you need to call UserPrivacy.Unwrap() before calling this method if this UserPrivacy
// was returned from a transaction, and the transaction was committed or rolled back.
func (up *UserPrivacy) Update() *UserPrivacyUpdateOne {
	return NewUserPrivacyClient(up.config).UpdateOne(up)
}

// Unwrap unwraps the UserPrivacy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (up *UserPrivacy) Unwrap() *UserPrivacy {
	_tx, ok := up.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPrivacy is not a transactional entity")
	}
	up.config.driver = _tx.drv
	return up
}

// String implements the fmt.Stringer.
func (up *UserPrivacy) String() string {
	var builder strings.Builder
	builder.WriteString("UserPrivacy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", up.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", up.UserID))
	builder.WriteString(", ")
	builder.WriteString("setting=")
	builder.WriteString(fmt.Sprintf("%v", up.Setting))
	builder.WriteString(", ")
	builder.WriteString("option=")
	builder.WriteString(fmt.Sprintf("%v", up.Option))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(up.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserPrivacies is a parsable slice of UserPrivacy.
type UserPrivacies []*UserPrivacy
