// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/iam/ent/predicate"
	"gitlab.calendaria.team/services/iam/ent/property"
	"gitlab.calendaria.team/services/iam/ent/user"
	"gitlab.calendaria.team/services/iam/ent/userprivacy"
)

// UserPrivacyUpdate is the builder for updating UserPrivacy entities.
type UserPrivacyUpdate struct {
	config
	hooks     []Hook
	mutation  *UserPrivacyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserPrivacyUpdate builder.
func (upu *UserPrivacyUpdate) Where(ps ...predicate.UserPrivacy) *UserPrivacyUpdate {
	upu.mutation.Where(ps...)
	return upu
}

// SetUserID sets the "user_id" field.
func (upu *UserPrivacyUpdate) SetUserID(i int64) *UserPrivacyUpdate {
	upu.mutation.SetUserID(i)
	return upu
}

// SetSetting sets the "setting" field.
func (upu *UserPrivacyUpdate) SetSetting(ps property.PrivacySettings) *UserPrivacyUpdate {
	upu.mutation.SetSetting(ps)
	return upu
}

// SetOption sets the "option" field.
func (upu *UserPrivacyUpdate) SetOption(po property.PrivacyOptions) *UserPrivacyUpdate {
	upu.mutation.SetOption(po)
	return upu
}

// SetUpdatedAt sets the "updated_at" field.
func (upu *UserPrivacyUpdate) SetUpdatedAt(t time.Time) *UserPrivacyUpdate {
	upu.mutation.SetUpdatedAt(t)
	return upu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (upu *UserPrivacyUpdate) SetNillableUpdatedAt(t *time.Time) *UserPrivacyUpdate {
	if t != nil {
		upu.SetUpdatedAt(*t)
	}
	return upu
}

// SetUser sets the "user" edge to the User entity.
func (upu *UserPrivacyUpdate) SetUser(u *User) *UserPrivacyUpdate {
	return upu.SetUserID(u.ID)
}

// Mutation returns the UserPrivacyMutation object of the builder.
func (upu *UserPrivacyUpdate) Mutation() *UserPrivacyMutation {
	return upu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (upu *UserPrivacyUpdate) ClearUser() *UserPrivacyUpdate {
	upu.mutation.ClearUser()
	return upu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (upu *UserPrivacyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, upu.sqlSave, upu.mutation, upu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upu *UserPrivacyUpdate) SaveX(ctx context.Context) int {
	affected, err := upu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (upu *UserPrivacyUpdate) Exec(ctx context.Context) error {
	_, err := upu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upu *UserPrivacyUpdate) ExecX(ctx context.Context) {
	if err := upu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upu *UserPrivacyUpdate) check() error {
	if v, ok := upu.mutation.Setting(); ok {
		if err := userprivacy.SettingValidator(v); err != nil {
			return &ValidationError{Name: "setting", err: fmt.Errorf(`ent: validator failed for field "UserPrivacy.setting": %w`, err)}
		}
	}
	if v, ok := upu.mutation.Option(); ok {
		if err := userprivacy.OptionValidator(v); err != nil {
			return &ValidationError{Name: "option", err: fmt.Errorf(`ent: validator failed for field "UserPrivacy.option": %w`, err)}
		}
	}
	if _, ok := upu.mutation.UserID(); upu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserPrivacy.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (upu *UserPrivacyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserPrivacyUpdate {
	upu.modifiers = append(upu.modifiers, modifiers...)
	return upu
}

func (upu *UserPrivacyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := upu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprivacy.Table, userprivacy.Columns, sqlgraph.NewFieldSpec(userprivacy.FieldID, field.TypeInt64))
	if ps := upu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upu.mutation.Setting(); ok {
		_spec.SetField(userprivacy.FieldSetting, field.TypeEnum, value)
	}
	if value, ok := upu.mutation.Option(); ok {
		_spec.SetField(userprivacy.FieldOption, field.TypeEnum, value)
	}
	if value, ok := upu.mutation.UpdatedAt(); ok {
		_spec.SetField(userprivacy.FieldUpdatedAt, field.TypeTime, value)
	}
	if upu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprivacy.UserTable,
			Columns: []string{userprivacy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprivacy.UserTable,
			Columns: []string{userprivacy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(upu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, upu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprivacy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	upu.mutation.done = true
	return n, nil
}

// UserPrivacyUpdateOne is the builder for updating a single UserPrivacy entity.
type UserPrivacyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserPrivacyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (upuo *UserPrivacyUpdateOne) SetUserID(i int64) *UserPrivacyUpdateOne {
	upuo.mutation.SetUserID(i)
	return upuo
}

// SetSetting sets the "setting" field.
func (upuo *UserPrivacyUpdateOne) SetSetting(ps property.PrivacySettings) *UserPrivacyUpdateOne {
	upuo.mutation.SetSetting(ps)
	return upuo
}

// SetOption sets the "option" field.
func (upuo *UserPrivacyUpdateOne) SetOption(po property.PrivacyOptions) *UserPrivacyUpdateOne {
	upuo.mutation.SetOption(po)
	return upuo
}

// SetUpdatedAt sets the "updated_at" field.
func (upuo *UserPrivacyUpdateOne) SetUpdatedAt(t time.Time) *UserPrivacyUpdateOne {
	upuo.mutation.SetUpdatedAt(t)
	return upuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (upuo *UserPrivacyUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserPrivacyUpdateOne {
	if t != nil {
		upuo.SetUpdatedAt(*t)
	}
	return upuo
}

// SetUser sets the "user" edge to the User entity.
func (upuo *UserPrivacyUpdateOne) SetUser(u *User) *UserPrivacyUpdateOne {
	return upuo.SetUserID(u.ID)
}

// Mutation returns the UserPrivacyMutation object of the builder.
func (upuo *UserPrivacyUpdateOne) Mutation() *UserPrivacyMutation {
	return upuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (upuo *UserPrivacyUpdateOne) ClearUser() *UserPrivacyUpdateOne {
	upuo.mutation.ClearUser()
	return upuo
}

// Where appends a list predicates to the UserPrivacyUpdate builder.
func (upuo *UserPrivacyUpdateOne) Where(ps ...predicate.UserPrivacy) *UserPrivacyUpdateOne {
	upuo.mutation.Where(ps...)
	return upuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (upuo *UserPrivacyUpdateOne) Select(field string, fields ...string) *UserPrivacyUpdateOne {
	upuo.fields = append([]string{field}, fields...)
	return upuo
}

// Save executes the query and returns the updated UserPrivacy entity.
func (upuo *UserPrivacyUpdateOne) Save(ctx context.Context) (*UserPrivacy, error) {
	return withHooks(ctx, upuo.sqlSave, upuo.mutation, upuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upuo *UserPrivacyUpdateOne) SaveX(ctx context.Context) *UserPrivacy {
	node, err := upuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (upuo *UserPrivacyUpdateOne) Exec(ctx context.Context) error {
	_, err := upuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upuo *UserPrivacyUpdateOne) ExecX(ctx context.Context) {
	if err := upuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upuo *UserPrivacyUpdateOne) check() error {
	if v, ok := upuo.mutation.Setting(); ok {
		if err := userprivacy.SettingValidator(v); err != nil {
			return &ValidationError{Name: "setting", err: fmt.Errorf(`ent: validator failed for field "UserPrivacy.setting": %w`, err)}
		}
	}
	if v, ok := upuo.mutation.Option(); ok {
		if err := userprivacy.OptionValidator(v); err != nil {
			return &ValidationError{Name: "option", err: fmt.Errorf(`ent: validator failed for field "UserPrivacy.option": %w`, err)}
		}
	}
	if _, ok := upuo.mutation.UserID(); upuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserPrivacy.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (upuo *UserPrivacyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserPrivacyUpdateOne {
	upuo.modifiers = append(upuo.modifiers, modifiers...)
	return upuo
}

func (upuo *UserPrivacyUpdateOne) sqlSave(ctx context.Context) (_node *UserPrivacy, err error) {
	if err := upuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprivacy.Table, userprivacy.Columns, sqlgraph.NewFieldSpec(userprivacy.FieldID, field.TypeInt64))
	id, ok := upuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPrivacy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := upuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprivacy.FieldID)
		for _, f := range fields {
			if !userprivacy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userprivacy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := upuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upuo.mutation.Setting(); ok {
		_spec.SetField(userprivacy.FieldSetting, field.TypeEnum, value)
	}
	if value, ok := upuo.mutation.Option(); ok {
		_spec.SetField(userprivacy.FieldOption, field.TypeEnum, value)
	}
	if value, ok := upuo.mutation.UpdatedAt(); ok {
		_spec.SetField(userprivacy.FieldUpdatedAt, field.TypeTime, value)
	}
	if upuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprivacy.UserTable,
			Columns: []string{userprivacy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprivacy.UserTable,
			Columns: []string{userprivacy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(upuo.modifiers...)
	_node = &UserPrivacy{config: upuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, upuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprivacy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	upuo.mutation.done = true
	return _node, nil
}
