// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/iam/ent/predicate"
	"github.com/makesalekz/iam/ent/user"
	"github.com/makesalekz/iam/ent/usercredentials"
)

// UserCredentialsQuery is the builder for querying UserCredentials entities.
type UserCredentialsQuery struct {
	config
	ctx        *QueryContext
	order      []usercredentials.OrderOption
	inters     []Interceptor
	predicates []predicate.UserCredentials
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserCredentialsQuery builder.
func (ucq *UserCredentialsQuery) Where(ps ...predicate.UserCredentials) *UserCredentialsQuery {
	ucq.predicates = append(ucq.predicates, ps...)
	return ucq
}

// Limit the number of records to be returned by this query.
func (ucq *UserCredentialsQuery) Limit(limit int) *UserCredentialsQuery {
	ucq.ctx.Limit = &limit
	return ucq
}

// Offset to start from.
func (ucq *UserCredentialsQuery) Offset(offset int) *UserCredentialsQuery {
	ucq.ctx.Offset = &offset
	return ucq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ucq *UserCredentialsQuery) Unique(unique bool) *UserCredentialsQuery {
	ucq.ctx.Unique = &unique
	return ucq
}

// Order specifies how the records should be ordered.
func (ucq *UserCredentialsQuery) Order(o ...usercredentials.OrderOption) *UserCredentialsQuery {
	ucq.order = append(ucq.order, o...)
	return ucq
}

// QueryUser chains the current query on the "user" edge.
func (ucq *UserCredentialsQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ucq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ucq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usercredentials.Table, usercredentials.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usercredentials.UserTable, usercredentials.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ucq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserCredentials entity from the query.
// Returns a *NotFoundError when no UserCredentials was found.
func (ucq *UserCredentialsQuery) First(ctx context.Context) (*UserCredentials, error) {
	nodes, err := ucq.Limit(1).All(setContextOp(ctx, ucq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usercredentials.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ucq *UserCredentialsQuery) FirstX(ctx context.Context) *UserCredentials {
	node, err := ucq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserCredentials ID from the query.
// Returns a *NotFoundError when no UserCredentials ID was found.
func (ucq *UserCredentialsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ucq.Limit(1).IDs(setContextOp(ctx, ucq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usercredentials.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ucq *UserCredentialsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ucq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserCredentials entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserCredentials entity is found.
// Returns a *NotFoundError when no UserCredentials entities are found.
func (ucq *UserCredentialsQuery) Only(ctx context.Context) (*UserCredentials, error) {
	nodes, err := ucq.Limit(2).All(setContextOp(ctx, ucq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usercredentials.Label}
	default:
		return nil, &NotSingularError{usercredentials.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ucq *UserCredentialsQuery) OnlyX(ctx context.Context) *UserCredentials {
	node, err := ucq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserCredentials ID in the query.
// Returns a *NotSingularError when more than one UserCredentials ID is found.
// Returns a *NotFoundError when no entities are found.
func (ucq *UserCredentialsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ucq.Limit(2).IDs(setContextOp(ctx, ucq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usercredentials.Label}
	default:
		err = &NotSingularError{usercredentials.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ucq *UserCredentialsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ucq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserCredentialsSlice.
func (ucq *UserCredentialsQuery) All(ctx context.Context) ([]*UserCredentials, error) {
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryAll)
	if err := ucq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserCredentials, *UserCredentialsQuery]()
	return withInterceptors[[]*UserCredentials](ctx, ucq, qr, ucq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ucq *UserCredentialsQuery) AllX(ctx context.Context) []*UserCredentials {
	nodes, err := ucq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserCredentials IDs.
func (ucq *UserCredentialsQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ucq.ctx.Unique == nil && ucq.path != nil {
		ucq.Unique(true)
	}
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryIDs)
	if err = ucq.Select(usercredentials.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ucq *UserCredentialsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ucq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ucq *UserCredentialsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryCount)
	if err := ucq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ucq, querierCount[*UserCredentialsQuery](), ucq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ucq *UserCredentialsQuery) CountX(ctx context.Context) int {
	count, err := ucq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ucq *UserCredentialsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryExist)
	switch _, err := ucq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ucq *UserCredentialsQuery) ExistX(ctx context.Context) bool {
	exist, err := ucq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserCredentialsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ucq *UserCredentialsQuery) Clone() *UserCredentialsQuery {
	if ucq == nil {
		return nil
	}
	return &UserCredentialsQuery{
		config:     ucq.config,
		ctx:        ucq.ctx.Clone(),
		order:      append([]usercredentials.OrderOption{}, ucq.order...),
		inters:     append([]Interceptor{}, ucq.inters...),
		predicates: append([]predicate.UserCredentials{}, ucq.predicates...),
		withUser:   ucq.withUser.Clone(),
		// clone intermediate query.
		sql:       ucq.sql.Clone(),
		path:      ucq.path,
		modifiers: append([]func(*sql.Selector){}, ucq.modifiers...),
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ucq *UserCredentialsQuery) WithUser(opts ...func(*UserQuery)) *UserCredentialsQuery {
	query := (&UserClient{config: ucq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ucq.withUser = query
	return ucq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserCredentials.Query().
//		GroupBy(usercredentials.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ucq *UserCredentialsQuery) GroupBy(field string, fields ...string) *UserCredentialsGroupBy {
	ucq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserCredentialsGroupBy{build: ucq}
	grbuild.flds = &ucq.ctx.Fields
	grbuild.label = usercredentials.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UserCredentials.Query().
//		Select(usercredentials.FieldCreatedAt).
//		Scan(ctx, &v)
func (ucq *UserCredentialsQuery) Select(fields ...string) *UserCredentialsSelect {
	ucq.ctx.Fields = append(ucq.ctx.Fields, fields...)
	sbuild := &UserCredentialsSelect{UserCredentialsQuery: ucq}
	sbuild.label = usercredentials.Label
	sbuild.flds, sbuild.scan = &ucq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserCredentialsSelect configured with the given aggregations.
func (ucq *UserCredentialsQuery) Aggregate(fns ...AggregateFunc) *UserCredentialsSelect {
	return ucq.Select().Aggregate(fns...)
}

func (ucq *UserCredentialsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ucq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ucq); err != nil {
				return err
			}
		}
	}
	for _, f := range ucq.ctx.Fields {
		if !usercredentials.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ucq.path != nil {
		prev, err := ucq.path(ctx)
		if err != nil {
			return err
		}
		ucq.sql = prev
	}
	return nil
}

func (ucq *UserCredentialsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserCredentials, error) {
	var (
		nodes       = []*UserCredentials{}
		_spec       = ucq.querySpec()
		loadedTypes = [1]bool{
			ucq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserCredentials).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserCredentials{config: ucq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ucq.modifiers) > 0 {
		_spec.Modifiers = ucq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ucq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ucq.withUser; query != nil {
		if err := ucq.loadUser(ctx, query, nodes, nil,
			func(n *UserCredentials, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ucq *UserCredentialsQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserCredentials, init func(*UserCredentials), assign func(*UserCredentials, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserCredentials)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ucq *UserCredentialsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ucq.querySpec()
	if len(ucq.modifiers) > 0 {
		_spec.Modifiers = ucq.modifiers
	}
	_spec.Node.Columns = ucq.ctx.Fields
	if len(ucq.ctx.Fields) > 0 {
		_spec.Unique = ucq.ctx.Unique != nil && *ucq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ucq.driver, _spec)
}

func (ucq *UserCredentialsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usercredentials.Table, usercredentials.Columns, sqlgraph.NewFieldSpec(usercredentials.FieldID, field.TypeInt64))
	_spec.From = ucq.sql
	if unique := ucq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ucq.path != nil {
		_spec.Unique = true
	}
	if fields := ucq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercredentials.FieldID)
		for i := range fields {
			if fields[i] != usercredentials.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ucq.withUser != nil {
			_spec.Node.AddColumnOnce(usercredentials.FieldUserID)
		}
	}
	if ps := ucq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ucq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ucq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ucq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ucq *UserCredentialsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ucq.driver.Dialect())
	t1 := builder.Table(usercredentials.Table)
	columns := ucq.ctx.Fields
	if len(columns) == 0 {
		columns = usercredentials.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ucq.sql != nil {
		selector = ucq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ucq.ctx.Unique != nil && *ucq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ucq.modifiers {
		m(selector)
	}
	for _, p := range ucq.predicates {
		p(selector)
	}
	for _, p := range ucq.order {
		p(selector)
	}
	if offset := ucq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ucq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ucq *UserCredentialsQuery) Modify(modifiers ...func(s *sql.Selector)) *UserCredentialsSelect {
	ucq.modifiers = append(ucq.modifiers, modifiers...)
	return ucq.Select()
}

// UserCredentialsGroupBy is the group-by builder for UserCredentials entities.
type UserCredentialsGroupBy struct {
	selector
	build *UserCredentialsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ucgb *UserCredentialsGroupBy) Aggregate(fns ...AggregateFunc) *UserCredentialsGroupBy {
	ucgb.fns = append(ucgb.fns, fns...)
	return ucgb
}

// Scan applies the selector query and scans the result into the given value.
func (ucgb *UserCredentialsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ucgb.build.ctx, ent.OpQueryGroupBy)
	if err := ucgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserCredentialsQuery, *UserCredentialsGroupBy](ctx, ucgb.build, ucgb, ucgb.build.inters, v)
}

func (ucgb *UserCredentialsGroupBy) sqlScan(ctx context.Context, root *UserCredentialsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ucgb.fns))
	for _, fn := range ucgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ucgb.flds)+len(ucgb.fns))
		for _, f := range *ucgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ucgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserCredentialsSelect is the builder for selecting fields of UserCredentials entities.
type UserCredentialsSelect struct {
	*UserCredentialsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ucs *UserCredentialsSelect) Aggregate(fns ...AggregateFunc) *UserCredentialsSelect {
	ucs.fns = append(ucs.fns, fns...)
	return ucs
}

// Scan applies the selector query and scans the result into the given value.
func (ucs *UserCredentialsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ucs.ctx, ent.OpQuerySelect)
	if err := ucs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserCredentialsQuery, *UserCredentialsSelect](ctx, ucs.UserCredentialsQuery, ucs, ucs.inters, v)
}

func (ucs *UserCredentialsSelect) sqlScan(ctx context.Context, root *UserCredentialsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ucs.fns))
	for _, fn := range ucs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ucs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ucs *UserCredentialsSelect) Modify(modifiers ...func(s *sql.Selector)) *UserCredentialsSelect {
	ucs.modifiers = append(ucs.modifiers, modifiers...)
	return ucs
}
