// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/iam/ent/enum"
	"gitlab.calendaria.team/services/iam/ent/user"
	"gitlab.calendaria.team/services/iam/ent/usercredentials"
)

// UserCredentials is the model entity for the UserCredentials schema.
type UserCredentials struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Mail holds the value of the "mail" field.
	Mail *string `json:"mail,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName *string `json:"display_name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider *enum.Provider `json:"provider,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// TokenType holds the value of the "token_type" field.
	TokenType *string `json:"token_type,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken *string `json:"refresh_token,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCredentialsQuery when eager-loading is set.
	Edges        UserCredentialsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserCredentialsEdges holds the relations/edges for other nodes in the graph.
type UserCredentialsEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCredentialsEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCredentials) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercredentials.FieldID, usercredentials.FieldUserID:
			values[i] = new(sql.NullInt64)
		case usercredentials.FieldMail, usercredentials.FieldDisplayName, usercredentials.FieldProvider, usercredentials.FieldAccessToken, usercredentials.FieldTokenType, usercredentials.FieldRefreshToken:
			values[i] = new(sql.NullString)
		case usercredentials.FieldDeletedAt, usercredentials.FieldExpiresAt, usercredentials.FieldCreatedAt, usercredentials.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCredentials fields.
func (uc *UserCredentials) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercredentials.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			uc.ID = int64(value.Int64)
		case usercredentials.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				uc.DeletedAt = new(time.Time)
				*uc.DeletedAt = value.Time
			}
		case usercredentials.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				uc.UserID = value.Int64
			}
		case usercredentials.FieldMail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mail", values[i])
			} else if value.Valid {
				uc.Mail = new(string)
				*uc.Mail = value.String
			}
		case usercredentials.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				uc.DisplayName = new(string)
				*uc.DisplayName = value.String
			}
		case usercredentials.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				uc.Provider = new(enum.Provider)
				*uc.Provider = enum.Provider(value.String)
			}
		case usercredentials.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				uc.AccessToken = value.String
			}
		case usercredentials.FieldTokenType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_type", values[i])
			} else if value.Valid {
				uc.TokenType = new(string)
				*uc.TokenType = value.String
			}
		case usercredentials.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				uc.RefreshToken = new(string)
				*uc.RefreshToken = value.String
			}
		case usercredentials.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				uc.ExpiresAt = new(time.Time)
				*uc.ExpiresAt = value.Time
			}
		case usercredentials.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				uc.CreatedAt = value.Time
			}
		case usercredentials.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				uc.UpdatedAt = value.Time
			}
		default:
			uc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCredentials.
// This includes values selected through modifiers, order, etc.
func (uc *UserCredentials) Value(name string) (ent.Value, error) {
	return uc.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserCredentials entity.
func (uc *UserCredentials) QueryUser() *UserQuery {
	return NewUserCredentialsClient(uc.config).QueryUser(uc)
}

// Update returns a builder for updating this UserCredentials.
// Note that you need to call UserCredentials.Unwrap() before calling this method if this UserCredentials
// was returned from a transaction, and the transaction was committed or rolled back.
func (uc *UserCredentials) Update() *UserCredentialsUpdateOne {
	return NewUserCredentialsClient(uc.config).UpdateOne(uc)
}

// Unwrap unwraps the UserCredentials entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uc *UserCredentials) Unwrap() *UserCredentials {
	_tx, ok := uc.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCredentials is not a transactional entity")
	}
	uc.config.driver = _tx.drv
	return uc
}

// String implements the fmt.Stringer.
func (uc *UserCredentials) String() string {
	var builder strings.Builder
	builder.WriteString("UserCredentials(")
	builder.WriteString(fmt.Sprintf("id=%v, ", uc.ID))
	if v := uc.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", uc.UserID))
	builder.WriteString(", ")
	if v := uc.Mail; v != nil {
		builder.WriteString("mail=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := uc.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := uc.Provider; v != nil {
		builder.WriteString("provider=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(uc.AccessToken)
	builder.WriteString(", ")
	if v := uc.TokenType; v != nil {
		builder.WriteString("token_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := uc.RefreshToken; v != nil {
		builder.WriteString("refresh_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := uc.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(uc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(uc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserCredentialsSlice is a parsable slice of UserCredentials.
type UserCredentialsSlice []*UserCredentials
