server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
db:
  address: host=10.2.8.175 port=5432 user=iam dbname=iam password=shaev3neiZ@ah9k sslmode=disable
nats: nats://10.2.4.6:4222
discovery:
  notifications: discovery:///notifications
  notifications_timeout: 30s
  contacts: discovery:///contacts
  contacts_timeout: 30s
  tenants: discovery:///tenants
  tenants_timeout: 30s
  chats: discovery:///chats
  chats_timeout: 30s
