server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
db: host=localhost port=5432 user=me dbname=iam password=password sslmode=disable
nats: nats://localhost:4222
discovery:
  notifications: localhost:9003
  notifications_timeout: 30s
  tenants: localhost:9007
  tenants_timeout: 30s
  contacts: localhost:9006
  contacts_timeout: 30s
  chats: localhost:9002
  chats_timeout: 30s
  events: localhost:9005
  events_timeout: 30s
  media: localhost:9004
  media_timeout: 30s
  websockets: localhost:9015
  websockets_timeout: 30s