
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

pullPolicy: "Always"

imagePullSecrets: "regcred"
image:
  repository: ""
  nginx: ""

containerPort: 8000

type: ClusterIP
terminationGracePeriodSeconds: 60

limitsMemory: ""
limitsCPU: ""

requestsMemory: ""
requestsCPU: ""

