-- Create "user_settings" table
CREATE TABLE "user_settings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "setting" character varying NOT NULL, "value" character varying NOT NULL, "updated_at" timestamptz NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_settings_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "usersettings_user_id_setting" to table: "user_settings"
CREATE UNIQUE INDEX "usersettings_user_id_setting" ON "user_settings" ("user_id", "setting");
