// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: iam/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthByLoginPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthByLoginPasswordRequest) Reset() {
	*x = AuthByLoginPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthByLoginPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthByLoginPasswordRequest) ProtoMessage() {}

func (x *AuthByLoginPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthByLoginPasswordRequest.ProtoReflect.Descriptor instead.
func (*AuthByLoginPasswordRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthByLoginPasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthByLoginPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthByLoginPasswordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthByLoginPasswordReply) Reset() {
	*x = AuthByLoginPasswordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthByLoginPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthByLoginPasswordReply) ProtoMessage() {}

func (x *AuthByLoginPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthByLoginPasswordReply.ProtoReflect.Descriptor instead.
func (*AuthByLoginPasswordReply) Descriptor() ([]byte, []int) {
	return file_iam_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthByLoginPasswordReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthByPhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *AuthByPhoneRequest) Reset() {
	*x = AuthByPhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthByPhoneRequest) ProtoMessage() {}

func (x *AuthByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthByPhoneRequest.ProtoReflect.Descriptor instead.
func (*AuthByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type AuthByPhoneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *AuthByPhoneReply) Reset() {
	*x = AuthByPhoneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthByPhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthByPhoneReply) ProtoMessage() {}

func (x *AuthByPhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthByPhoneReply.ProtoReflect.Descriptor instead.
func (*AuthByPhoneReply) Descriptor() ([]byte, []int) {
	return file_iam_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthByPhoneReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AuthByPhoneCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AuthByPhoneCodeRequest) Reset() {
	*x = AuthByPhoneCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthByPhoneCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthByPhoneCodeRequest) ProtoMessage() {}

func (x *AuthByPhoneCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthByPhoneCodeRequest.ProtoReflect.Descriptor instead.
func (*AuthByPhoneCodeRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthByPhoneCodeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthByPhoneCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AuthByPhoneCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthByPhoneCodeReply) Reset() {
	*x = AuthByPhoneCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthByPhoneCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthByPhoneCodeReply) ProtoMessage() {}

func (x *AuthByPhoneCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthByPhoneCodeReply.ProtoReflect.Descriptor instead.
func (*AuthByPhoneCodeReply) Descriptor() ([]byte, []int) {
	return file_iam_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthByPhoneCodeReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_iam_v1_auth_proto protoreflect.FileDescriptor

var file_iam_v1_auth_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x61, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a,
	0x1a, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x30, 0x0a,
	0x18, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x2a, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x41,
	0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x42, 0x0a, 0x16, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x14, 0x41, 0x75, 0x74,
	0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xe7, 0x02, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x7e, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x3a, 0x01, 0x2a,
	0x22, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x66, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x3a, 0x01, 0x2a, 0x22, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x77, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68,
	0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a, 0x22, 0x13, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2d, 0x63, 0x6f, 0x64,
	0x65, 0x42, 0x21, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x11, 0x69, 0x61, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iam_v1_auth_proto_rawDescOnce sync.Once
	file_iam_v1_auth_proto_rawDescData = file_iam_v1_auth_proto_rawDesc
)

func file_iam_v1_auth_proto_rawDescGZIP() []byte {
	file_iam_v1_auth_proto_rawDescOnce.Do(func() {
		file_iam_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_iam_v1_auth_proto_rawDescData)
	})
	return file_iam_v1_auth_proto_rawDescData
}

var file_iam_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_iam_v1_auth_proto_goTypes = []interface{}{
	(*AuthByLoginPasswordRequest)(nil), // 0: api.iam.v1.AuthByLoginPasswordRequest
	(*AuthByLoginPasswordReply)(nil),   // 1: api.iam.v1.AuthByLoginPasswordReply
	(*AuthByPhoneRequest)(nil),         // 2: api.iam.v1.AuthByPhoneRequest
	(*AuthByPhoneReply)(nil),           // 3: api.iam.v1.AuthByPhoneReply
	(*AuthByPhoneCodeRequest)(nil),     // 4: api.iam.v1.AuthByPhoneCodeRequest
	(*AuthByPhoneCodeReply)(nil),       // 5: api.iam.v1.AuthByPhoneCodeReply
}
var file_iam_v1_auth_proto_depIdxs = []int32{
	0, // 0: api.iam.v1.Auth.AuthByLoginPassword:input_type -> api.iam.v1.AuthByLoginPasswordRequest
	2, // 1: api.iam.v1.Auth.AuthByPhone:input_type -> api.iam.v1.AuthByPhoneRequest
	4, // 2: api.iam.v1.Auth.AuthByPhoneCode:input_type -> api.iam.v1.AuthByPhoneCodeRequest
	1, // 3: api.iam.v1.Auth.AuthByLoginPassword:output_type -> api.iam.v1.AuthByLoginPasswordReply
	3, // 4: api.iam.v1.Auth.AuthByPhone:output_type -> api.iam.v1.AuthByPhoneReply
	5, // 5: api.iam.v1.Auth.AuthByPhoneCode:output_type -> api.iam.v1.AuthByPhoneCodeReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iam_v1_auth_proto_init() }
func file_iam_v1_auth_proto_init() {
	if File_iam_v1_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iam_v1_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthByLoginPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthByLoginPasswordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthByPhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthByPhoneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthByPhoneCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthByPhoneCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iam_v1_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_v1_auth_proto_goTypes,
		DependencyIndexes: file_iam_v1_auth_proto_depIdxs,
		MessageInfos:      file_iam_v1_auth_proto_msgTypes,
	}.Build()
	File_iam_v1_auth_proto = out.File
	file_iam_v1_auth_proto_rawDesc = nil
	file_iam_v1_auth_proto_goTypes = nil
	file_iam_v1_auth_proto_depIdxs = nil
}
