// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.24.4
// source: api/iam/v1/auth.proto

package iam_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuthAuthByCode = "/iam.v1.Auth/AuthByCode"
const OperationAuthAuthByPhone = "/iam.v1.Auth/AuthByPhone"
const OperationAuthRefreshToken = "/iam.v1.Auth/RefreshToken"

type AuthHTTPServer interface {
	// AuthByCode Auth by Code
	// after you authorized bu phone, you suppose to enter code that you've got here
	// request: id from AuthByPhone, code from message
	// returns: bearer token
	AuthByCode(context.Context, *AuthByCodeRequest) (*TokenReply, error)
	// AuthByPhone Auth by Phone
	// request: phone number
	// returns: id of newly created otp user
	AuthByPhone(context.Context, *AuthByPhoneRequest) (*AuthByPhoneReply, error)
	RefreshToken(context.Context, *TenantRequest) (*TokenReply, error)
}

func RegisterAuthHTTPServer(s *http.Server, srv AuthHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/auth/phone", _Auth_AuthByPhone0_HTTP_Handler(srv))
	r.POST("/v1/auth/code", _Auth_AuthByCode0_HTTP_Handler(srv))
	r.POST("/v1/auth/token", _Auth_RefreshToken0_HTTP_Handler(srv))
}

func _Auth_AuthByPhone0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthByPhoneRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthAuthByPhone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthByPhone(ctx, req.(*AuthByPhoneRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthByPhoneReply)
		return ctx.Result(200, reply)
	}
}

func _Auth_AuthByCode0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthByCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthAuthByCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthByCode(ctx, req.(*AuthByCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenReply)
		return ctx.Result(200, reply)
	}
}

func _Auth_RefreshToken0_HTTP_Handler(srv AuthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthRefreshToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshToken(ctx, req.(*TenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenReply)
		return ctx.Result(200, reply)
	}
}

type AuthHTTPClient interface {
	AuthByCode(ctx context.Context, req *AuthByCodeRequest, opts ...http.CallOption) (rsp *TokenReply, err error)
	AuthByPhone(ctx context.Context, req *AuthByPhoneRequest, opts ...http.CallOption) (rsp *AuthByPhoneReply, err error)
	RefreshToken(ctx context.Context, req *TenantRequest, opts ...http.CallOption) (rsp *TokenReply, err error)
}

type AuthHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthHTTPClient(client *http.Client) AuthHTTPClient {
	return &AuthHTTPClientImpl{client}
}

func (c *AuthHTTPClientImpl) AuthByCode(ctx context.Context, in *AuthByCodeRequest, opts ...http.CallOption) (*TokenReply, error) {
	var out TokenReply
	pattern := "/v1/auth/code"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthAuthByCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AuthHTTPClientImpl) AuthByPhone(ctx context.Context, in *AuthByPhoneRequest, opts ...http.CallOption) (*AuthByPhoneReply, error) {
	var out AuthByPhoneReply
	pattern := "/v1/auth/phone"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthAuthByPhone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AuthHTTPClientImpl) RefreshToken(ctx context.Context, in *TenantRequest, opts ...http.CallOption) (*TokenReply, error) {
	var out TokenReply
	pattern := "/v1/auth/token"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthRefreshToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
