// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: iam/v1/auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Auth_AuthByLoginPassword_FullMethodName = "/api.iam.v1.Auth/AuthByLoginPassword"
	Auth_AuthByPhone_FullMethodName         = "/api.iam.v1.Auth/AuthByPhone"
	Auth_AuthByPhoneCode_FullMethodName     = "/api.iam.v1.Auth/AuthByPhoneCode"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	AuthByLoginPassword(ctx context.Context, in *AuthByLoginPasswordRequest, opts ...grpc.CallOption) (*AuthByLoginPasswordReply, error)
	AuthByPhone(ctx context.Context, in *AuthByPhoneRequest, opts ...grpc.CallOption) (*AuthByPhoneReply, error)
	AuthByPhoneCode(ctx context.Context, in *AuthByPhoneCodeRequest, opts ...grpc.CallOption) (*AuthByPhoneCodeReply, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthByLoginPassword(ctx context.Context, in *AuthByLoginPasswordRequest, opts ...grpc.CallOption) (*AuthByLoginPasswordReply, error) {
	out := new(AuthByLoginPasswordReply)
	err := c.cc.Invoke(ctx, Auth_AuthByLoginPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthByPhone(ctx context.Context, in *AuthByPhoneRequest, opts ...grpc.CallOption) (*AuthByPhoneReply, error) {
	out := new(AuthByPhoneReply)
	err := c.cc.Invoke(ctx, Auth_AuthByPhone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthByPhoneCode(ctx context.Context, in *AuthByPhoneCodeRequest, opts ...grpc.CallOption) (*AuthByPhoneCodeReply, error) {
	out := new(AuthByPhoneCodeReply)
	err := c.cc.Invoke(ctx, Auth_AuthByPhoneCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	AuthByLoginPassword(context.Context, *AuthByLoginPasswordRequest) (*AuthByLoginPasswordReply, error)
	AuthByPhone(context.Context, *AuthByPhoneRequest) (*AuthByPhoneReply, error)
	AuthByPhoneCode(context.Context, *AuthByPhoneCodeRequest) (*AuthByPhoneCodeReply, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) AuthByLoginPassword(context.Context, *AuthByLoginPasswordRequest) (*AuthByLoginPasswordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthByLoginPassword not implemented")
}
func (UnimplementedAuthServer) AuthByPhone(context.Context, *AuthByPhoneRequest) (*AuthByPhoneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthByPhone not implemented")
}
func (UnimplementedAuthServer) AuthByPhoneCode(context.Context, *AuthByPhoneCodeRequest) (*AuthByPhoneCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthByPhoneCode not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_AuthByLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthByLoginPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthByLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthByLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthByLoginPassword(ctx, req.(*AuthByLoginPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthByPhone(ctx, req.(*AuthByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthByPhoneCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthByPhoneCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthByPhoneCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthByPhoneCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthByPhoneCode(ctx, req.(*AuthByPhoneCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.iam.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthByLoginPassword",
			Handler:    _Auth_AuthByLoginPassword_Handler,
		},
		{
			MethodName: "AuthByPhone",
			Handler:    _Auth_AuthByPhone_Handler,
		},
		{
			MethodName: "AuthByPhoneCode",
			Handler:    _Auth_AuthByPhoneCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/v1/auth.proto",
}
