// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: api/iam/v1/credentials.proto

package iam_v1

import (
	context "context"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Credentials_AuthByGoogle_FullMethodName = "/iam.v1.Credentials/AuthByGoogle"
	Credentials_GetOwnSync_FullMethodName   = "/iam.v1.Credentials/GetOwnSync"
	Credentials_DeleteSync_FullMethodName   = "/iam.v1.Credentials/DeleteSync"
)

// CredentialsClient is the client API for Credentials service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialsClient interface {
	AuthByGoogle(ctx context.Context, in *AuthByGoogleRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	GetOwnSync(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*CredentialsReply, error)
	DeleteSync(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
}

type credentialsClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialsClient(cc grpc.ClientConnInterface) CredentialsClient {
	return &credentialsClient{cc}
}

func (c *credentialsClient) AuthByGoogle(ctx context.Context, in *AuthByGoogleRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Credentials_AuthByGoogle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsClient) GetOwnSync(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*CredentialsReply, error) {
	out := new(CredentialsReply)
	err := c.cc.Invoke(ctx, Credentials_GetOwnSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsClient) DeleteSync(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Credentials_DeleteSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialsServer is the server API for Credentials service.
// All implementations must embed UnimplementedCredentialsServer
// for forward compatibility
type CredentialsServer interface {
	AuthByGoogle(context.Context, *AuthByGoogleRequest) (*v1.EmptyReply, error)
	GetOwnSync(context.Context, *v1.EmptyRequest) (*CredentialsReply, error)
	DeleteSync(context.Context, *CredentialsRequest) (*v1.EmptyReply, error)
	mustEmbedUnimplementedCredentialsServer()
}

// UnimplementedCredentialsServer must be embedded to have forward compatible implementations.
type UnimplementedCredentialsServer struct {
}

func (UnimplementedCredentialsServer) AuthByGoogle(context.Context, *AuthByGoogleRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthByGoogle not implemented")
}
func (UnimplementedCredentialsServer) GetOwnSync(context.Context, *v1.EmptyRequest) (*CredentialsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOwnSync not implemented")
}
func (UnimplementedCredentialsServer) DeleteSync(context.Context, *CredentialsRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSync not implemented")
}
func (UnimplementedCredentialsServer) mustEmbedUnimplementedCredentialsServer() {}

// UnsafeCredentialsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialsServer will
// result in compilation errors.
type UnsafeCredentialsServer interface {
	mustEmbedUnimplementedCredentialsServer()
}

func RegisterCredentialsServer(s grpc.ServiceRegistrar, srv CredentialsServer) {
	s.RegisterService(&Credentials_ServiceDesc, srv)
}

func _Credentials_AuthByGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthByGoogleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).AuthByGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Credentials_AuthByGoogle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).AuthByGoogle(ctx, req.(*AuthByGoogleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Credentials_GetOwnSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).GetOwnSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Credentials_GetOwnSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).GetOwnSync(ctx, req.(*v1.EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Credentials_DeleteSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).DeleteSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Credentials_DeleteSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).DeleteSync(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Credentials_ServiceDesc is the grpc.ServiceDesc for Credentials service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Credentials_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.Credentials",
	HandlerType: (*CredentialsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthByGoogle",
			Handler:    _Credentials_AuthByGoogle_Handler,
		},
		{
			MethodName: "GetOwnSync",
			Handler:    _Credentials_GetOwnSync_Handler,
		},
		{
			MethodName: "DeleteSync",
			Handler:    _Credentials_DeleteSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam/v1/credentials.proto",
}
