// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.0
// source: api/iam/v1/users.proto

package iam_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUsersDeleteOwnProfile = "/iam.v1.Users/DeleteOwnProfile"
const OperationUsersGetOwnProfile = "/iam.v1.Users/GetOwnProfile"
const OperationUsersGetUser = "/iam.v1.Users/GetUser"
const OperationUsersGetUserByFilter = "/iam.v1.Users/GetUserByFilter"
const OperationUsersGetUserByFilterFull = "/iam.v1.Users/GetUserByFilterFull"
const OperationUsersGetUserFull = "/iam.v1.Users/GetUserFull"
const OperationUsersGetUsers = "/iam.v1.Users/GetUsers"
const OperationUsersRegisterUser = "/iam.v1.Users/RegisterUser"
const OperationUsersUpdateOwnProfile = "/iam.v1.Users/UpdateOwnProfile"

type UsersHTTPServer interface {
	// DeleteOwnProfile DeleteOwnProfile
	// This is self explanotory, delete own profile
	DeleteOwnProfile(context.Context, *v1.EmptyRequest) (*v1.EmptyReply, error)
	// GetOwnProfile GetOwnProfile
	// This is self explanotory, returns own profile
	GetOwnProfile(context.Context, *v1.EmptyRequest) (*UserFullReply, error)
	// GetUser GetUser
	// get single user
	GetUser(context.Context, *GetUserRequest) (*UserReply, error)
	// GetUserByFilter in case of search by phone, search.email should not be present
	// in case of search by email, search.phone should not be present
	GetUserByFilter(context.Context, *GetUserByFilterRequest) (*UserReply, error)
	// GetUserByFilterFull in case of search by phone, search.email should not be present
	// in case of search by email, search.phone should not be present
	GetUserByFilterFull(context.Context, *GetUserByFilterRequest) (*UserFullReply, error)
	// GetUserFull GetUserFull
	// Returns full information about user
	// Request: userId of seeking user
	GetUserFull(context.Context, *GetUserRequest) (*UserFullReply, error)
	// GetUsers search goes by all fileds
	// t.m if you declare labels,emails,ids this method will return all
	// users that has these fields
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersReply, error)
	// RegisterUser UpdateOwnProfile
	// This is self explanotory, update own profile
	RegisterUser(context.Context, *UpdateOwnProfileRequest) (*UserFullReply, error)
	// UpdateOwnProfile UpdateOwnProfile
	// This is self explanotory, update own profile
	UpdateOwnProfile(context.Context, *UpdateOwnProfileRequest) (*UserFullReply, error)
}

func RegisterUsersHTTPServer(s *http.Server, srv UsersHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/users/me", _Users_GetOwnProfile0_HTTP_Handler(srv))
	r.POST("/v1/users/register", _Users_RegisterUser0_HTTP_Handler(srv))
	r.POST("/v1/users/me", _Users_UpdateOwnProfile0_HTTP_Handler(srv))
	r.DELETE("/v1/users/me", _Users_DeleteOwnProfile0_HTTP_Handler(srv))
	r.GET("/v1/users/{userId}/full", _Users_GetUserFull0_HTTP_Handler(srv))
	r.POST("/v1/users/user/full", _Users_GetUserByFilterFull0_HTTP_Handler(srv))
	r.GET("/v1/users/{userId}", _Users_GetUser0_HTTP_Handler(srv))
	r.POST("/v1/users/user", _Users_GetUserByFilter0_HTTP_Handler(srv))
	r.POST("/v1/users/list", _Users_GetUsers0_HTTP_Handler(srv))
}

func _Users_GetOwnProfile0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.EmptyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersGetOwnProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOwnProfile(ctx, req.(*v1.EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserFullReply)
		return ctx.Result(200, reply)
	}
}

func _Users_RegisterUser0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOwnProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersRegisterUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterUser(ctx, req.(*UpdateOwnProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserFullReply)
		return ctx.Result(200, reply)
	}
}

func _Users_UpdateOwnProfile0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOwnProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersUpdateOwnProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOwnProfile(ctx, req.(*UpdateOwnProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserFullReply)
		return ctx.Result(200, reply)
	}
}

func _Users_DeleteOwnProfile0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.EmptyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersDeleteOwnProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteOwnProfile(ctx, req.(*v1.EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Users_GetUserFull0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersGetUserFull)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserFull(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserFullReply)
		return ctx.Result(200, reply)
	}
}

func _Users_GetUserByFilterFull0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserByFilterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersGetUserByFilterFull)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserByFilterFull(ctx, req.(*GetUserByFilterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserFullReply)
		return ctx.Result(200, reply)
	}
}

func _Users_GetUser0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserReply)
		return ctx.Result(200, reply)
	}
}

func _Users_GetUserByFilter0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserByFilterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersGetUserByFilter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserByFilter(ctx, req.(*GetUserByFilterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserReply)
		return ctx.Result(200, reply)
	}
}

func _Users_GetUsers0_HTTP_Handler(srv UsersHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUsersRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersGetUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUsers(ctx, req.(*GetUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUsersReply)
		return ctx.Result(200, reply)
	}
}

type UsersHTTPClient interface {
	DeleteOwnProfile(ctx context.Context, req *v1.EmptyRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
	GetOwnProfile(ctx context.Context, req *v1.EmptyRequest, opts ...http.CallOption) (rsp *UserFullReply, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *UserReply, err error)
	GetUserByFilter(ctx context.Context, req *GetUserByFilterRequest, opts ...http.CallOption) (rsp *UserReply, err error)
	GetUserByFilterFull(ctx context.Context, req *GetUserByFilterRequest, opts ...http.CallOption) (rsp *UserFullReply, err error)
	GetUserFull(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *UserFullReply, err error)
	GetUsers(ctx context.Context, req *GetUsersRequest, opts ...http.CallOption) (rsp *GetUsersReply, err error)
	RegisterUser(ctx context.Context, req *UpdateOwnProfileRequest, opts ...http.CallOption) (rsp *UserFullReply, err error)
	UpdateOwnProfile(ctx context.Context, req *UpdateOwnProfileRequest, opts ...http.CallOption) (rsp *UserFullReply, err error)
}

type UsersHTTPClientImpl struct {
	cc *http.Client
}

func NewUsersHTTPClient(client *http.Client) UsersHTTPClient {
	return &UsersHTTPClientImpl{client}
}

func (c *UsersHTTPClientImpl) DeleteOwnProfile(ctx context.Context, in *v1.EmptyRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/users/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUsersDeleteOwnProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) GetOwnProfile(ctx context.Context, in *v1.EmptyRequest, opts ...http.CallOption) (*UserFullReply, error) {
	var out UserFullReply
	pattern := "/v1/users/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUsersGetOwnProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*UserReply, error) {
	var out UserReply
	pattern := "/v1/users/{userId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUsersGetUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) GetUserByFilter(ctx context.Context, in *GetUserByFilterRequest, opts ...http.CallOption) (*UserReply, error) {
	var out UserReply
	pattern := "/v1/users/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersGetUserByFilter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) GetUserByFilterFull(ctx context.Context, in *GetUserByFilterRequest, opts ...http.CallOption) (*UserFullReply, error) {
	var out UserFullReply
	pattern := "/v1/users/user/full"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersGetUserByFilterFull))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) GetUserFull(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*UserFullReply, error) {
	var out UserFullReply
	pattern := "/v1/users/{userId}/full"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUsersGetUserFull))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...http.CallOption) (*GetUsersReply, error) {
	var out GetUsersReply
	pattern := "/v1/users/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersGetUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) RegisterUser(ctx context.Context, in *UpdateOwnProfileRequest, opts ...http.CallOption) (*UserFullReply, error) {
	var out UserFullReply
	pattern := "/v1/users/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersRegisterUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UsersHTTPClientImpl) UpdateOwnProfile(ctx context.Context, in *UpdateOwnProfileRequest, opts ...http.CallOption) (*UserFullReply, error) {
	var out UserFullReply
	pattern := "/v1/users/me"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersUpdateOwnProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
