// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OneTimePassword is the predicate function for onetimepassword builders.
type OneTimePassword func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPrivacy is the predicate function for userprivacy builders.
type UserPrivacy func(*sql.Selector)
